//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmWebApiEarlyBoundGenerator {
    using System.Reflection;
    using System.Linq;
    using System;
    using System.Collections.Generic;
    using System.Dynamic;
    using System.Diagnostics.CodeAnalysis;
    
    
    [ExcludeFromCodeCoverageAttribute()]
    public class qm_rclegislation_tylegislationcharacterist : Entity {
        
        public new const string EntityLogicalName = "qm_rclegislation_tylegislationcharacterist";
        
        public new const string EntitySetName = "qm_rclegislation_tylegislationcharacteristset";
        
        public new const string PrimaryIdAttribute = "qm_rclegislation_tylegislationcharacteristid";
        
        public qm_rclegislation_tylegislationcharacterist() {
        }
        
        public qm_rclegislation_tylegislationcharacterist(ExpandoObject expandoObject) : 
                base(expandoObject) {
        }
        
        public Guid? qm_rclegislation_tylegislationcharacteristId {
            get {
                return this.GetAttributeValue<Guid?>("qm_rclegislation_tylegislationcharacteristId");
            }
            set {
                this.SetAttributeValue("qm_rclegislation_tylegislationcharacteristId", value);
            }
        }
        
        public Guid? qm_rclegislationid {
            get {
                return this.GetAttributeValue<Guid?>("qm_rclegislationid");
            }
            set {
                this.SetAttributeValue("qm_rclegislationid", value);
            }
        }
        
        public Guid? qm_tylegislationcharacteristicid {
            get {
                return this.GetAttributeValue<Guid?>("qm_tylegislationcharacteristicid");
            }
            set {
                this.SetAttributeValue("qm_tylegislationcharacteristicid", value);
            }
        }
        
        public long? VersionNumber {
            get {
                return this.GetAttributeValue<long?>("VersionNumber");
            }
            set {
                this.SetAttributeValue("VersionNumber", value);
            }
        }
        
        public class Fields {
            
            public const string qm_rclegislation_tylegislationcharacteristId = "qm_rclegislation_tylegislationcharacteristid";
            
            public const string qm_rclegislationid = "qm_rclegislationid";
            
            public const string qm_tylegislationcharacteristicid = "qm_tylegislationcharacteristicid";
            
            public const string VersionNumber = "versionnumber";
            
            public const string Id = "qm_rclegislation_tylegislationcharacteristid";
        }
        
        public class Properties {
            
            public const string qm_rclegislation_tylegislationcharacteristic = "qm_rclegislation_tylegislationcharacteristic";
        }
        
        public class Schemas {
            
            public const string qm_rclegislation_tylegislationcharacteristId = "qm_rclegislation_tylegislationcharacteristId";
            
            public const string qm_rclegislationid = "qm_rclegislationid";
            
            public const string qm_tylegislationcharacteristicid = "qm_tylegislationcharacteristicid";
            
            public const string VersionNumber = "VersionNumber";
        }
    }
}
