//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TC.Legislation.EarlyBound {
    using System.Reflection;
    using System.Linq;
    using System;
    using System.Collections.Generic;
    using System.Dynamic;
    using System.Diagnostics.CodeAnalysis;
    
    
    [ExcludeFromCodeCoverageAttribute()]
    public class qm_sytemplate_sygroup : Entity {
        
        public new const string EntityLogicalName = "qm_sytemplate_sygroup";
        
        public new const string EntitySetName = "qm_sytemplate_sygroupset";
        
        public new const string PrimaryIdAttribute = "qm_sytemplate_sygroupid";
        
        public qm_sytemplate_sygroup() {
        }
        
        public qm_sytemplate_sygroup(ExpandoObject expandoObject) : 
                base(expandoObject) {
        }
        
        public Guid? qm_sygroupid {
            get {
                return this.GetAttributeValue<Guid?>("qm_sygroupid");
            }
            set {
                this.SetAttributeValue("qm_sygroupid", value);
            }
        }
        
        public Guid? qm_sytemplate_sygroupId {
            get {
                return this.GetAttributeValue<Guid?>("qm_sytemplate_sygroupId");
            }
            set {
                this.SetAttributeValue("qm_sytemplate_sygroupId", value);
            }
        }
        
        public Guid? qm_sytemplateid {
            get {
                return this.GetAttributeValue<Guid?>("qm_sytemplateid");
            }
            set {
                this.SetAttributeValue("qm_sytemplateid", value);
            }
        }
        
        public long? VersionNumber {
            get {
                return this.GetAttributeValue<long?>("VersionNumber");
            }
            set {
                this.SetAttributeValue("VersionNumber", value);
            }
        }
        
        public class Fields {
            
            public const string qm_sygroupid = "qm_sygroupid";
            
            public const string qm_sytemplate_sygroupId = "qm_sytemplate_sygroupid";
            
            public const string qm_sytemplateid = "qm_sytemplateid";
            
            public const string VersionNumber = "versionnumber";
            
            public const string Id = "qm_sytemplate_sygroupid";
        }
        
        public class Properties {
            
            public const string qm_sytemplate_sygroup = "qm_sytemplate_sygroup";
        }
        
        public class Schemas {
            
            public const string qm_sygroupid = "qm_sygroupid";
            
            public const string qm_sytemplate_sygroupId = "qm_sytemplate_sygroupId";
            
            public const string qm_sytemplateid = "qm_sytemplateid";
            
            public const string VersionNumber = "VersionNumber";
        }
    }
}
