/****** Object:  Table [dbo].[01_IIS_DATA_CONSOLIDATION]    Script Date: 2021-03-25 9:30:08 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

DROP TABLE IF EXISTS [dbo].SOURCE__DATA_CONSOLIDATION;
CREATE TABLE [dbo].SOURCE__DATA_CONSOLIDATION (
	[COMPLETED] [nvarchar](10) NULL,
	[ASSIGNED_TO] [nvarchar](100) NULL,
	[IIS_ID] [numeric](18, 0) NULL,
	[COMPANY_NAME_FORMATTED] [nvarchar](500) NULL,
	[PLANNED2021] [nvarchar](10) NULL,
	[COMPANY_NAME] [nvarchar](500) NULL,
	[COUNTRY_SUBDIVISION_CD] [nvarchar](10) NULL,
	[CITY_TOWN_NAME_NM] [nvarchar](250) NULL,
	[ADDRESS] [nvarchar](1000) NULL,
	[POSTAL_CODE_TXT] [nvarchar](10) NULL,
	[FILE_STATUS_CD] [nvarchar](50) NULL,
	[SOUNDEX_NAME] [nvarchar](50) NULL,
	[MATCHING_ID] [numeric](18, 0) NULL,
	[FUZZY_MATCH] [nvarchar](500) NULL,
	[REGULATED_ENTITY_ID] [nvarchar](50) NULL,
	[REGULATED_ENTITY_NAME] [nvarchar](500) NULL,
	[CONSOLIDATED_COMMON_ENGLISH_NAME] [nvarchar](500) NULL,
	[CONSOLIDATED_COMMON_FRENCH_NAME] [nvarchar](500) NULL,
	[NOTES] [nvarchar](500) NULL
) ON [PRIMARY]
GO


DROP TABLE IF EXISTS [dbo].[SOURCE__TERRITORY_TRANSLATION];
CREATE TABLE [dbo].[05_TERRITORY_TRANSLATION] (
    [COUNTRY_SUBDIVISION_CD] nvarchar(10),
	[msdyn_serviceterritory] uniqueidentifier
) ON [PRIMARY]
GO



/****** Object:  Table [dbo].[08_NOP_IMPORT]    Script Date: 2021-04-05 9:08:01 PM ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[08_NOP_IMPORT]') AND type in (N'U'))
DROP TABLE [dbo].[SOURCE__NOP_IMPORT]
GO

CREATE TABLE [dbo].[SOURCE__NOP_IMPORT](
	[IIS_ID] [numeric](18, 0) NULL,
	[MOC_ID] [numeric](18, 0) NULL,
	[PREFIX] [nvarchar](20) NULL,
	[COMPANY_NAME] [nvarchar](500) NULL,
	[ADDRESS] [nvarchar](500) NULL,
	[POSTALCODE] [nvarchar](20) NULL,
	[CITY] [nvarchar](100) NULL,
	[ACTIVITY_ID] [numeric](18, 0) NULL,
	[PROVINCE] [nvarchar](20) NULL,
	[ZONE] [nvarchar](100) NULL,
	[REGION_provincial] [nvarchar](20) NULL,
	[REGION_inspector] [nvarchar](20) NULL,
	[REGION_IIS] [nvarchar](20) NULL,
	[PLANNED_INSPECTOR] [nvarchar](100) NULL,
	[Quarter_1] [bit] NULL,
	[Quarter_2] [bit] NULL,
	[Quarter_3] [bit] NULL,
	[Quarter_4] [bit] NULL,
	[PLANNED_SITE] [bit] NULL,
	[DUE_PRIORITY] [nvarchar](20) NULL,
	[ACTIVITY_type_main_iis] [nvarchar](100) NULL,
	[ACTIVITY_type_sub_iis] [nvarchar](100) NULL,
	[inspector_name1] [nvarchar](100) NULL,
	[inspector_name2] [nvarchar](100) NULL,
	[INSPECTION_DATE_DTE] [datetime] NULL,
	[VERIFICATION_IND] [bit] NULL,
	[DATE_CREATED_DTE] [datetime] NULL,
	[FILE_REMARKS_TXT] [text] NULL,
	[FILE_STATUS_CD] [nvarchar](20) NULL,
	[DATE_CURRENT_DTE] [datetime] NULL,
	[DATE_DELETED_DTE] [datetime] NULL,
	[DATE_LAST_UPDATE_DTE] [datetime] NULL,
	[CONSIGNMENT_IND] [bit] NULL,
	[CEP_Complete] [nvarchar](20) NULL,
	[REPORT_CATEGORY] [nvarchar](100) NULL,
	[REPORT_REGION] [nvarchar](20) NULL,
	[REPORT_QUARTER] [nvarchar](10) NULL,
	[FINAL_TABLE] [nvarchar](20) NULL,
	[CEP_duplicate] [bit] NULL,
	[MORE_THAN_PLANNED] [bit] NULL,
	[HARDCODED] [bit] NULL,
	[REVIEWED_BY_HQ] [bit] NULL,
	[FLAGGED_FOR_REGIONAL_REVIEW] [bit] NULL,
	[ACTION_REQUIRED] [nvarchar](1000) NULL,
	[MOC_SUBTYPE_ERROR] [nvarchar](1000) NULL,
	[activity_type_enm_full] [nvarchar](100) NULL,
	[HQ_ONLY_FLAG] [bit] NULL,
	[hubs_flag] [bit] NULL,
	[TYPE] [nvarchar](10) NULL,
	[CEP_WARNING] [nvarchar](100) NULL,
	[Cep_sample_flag] [bit] NULL,
	[MOC_SV_FLAG] [bit] NULL,
	[COVID_FLAG] [bit] NULL,
	[ACTIVITY_HARDCODED] [bit] NULL,
	[REGION_HARDCODED] [bit] NULL,
	[PRINTED] [nvarchar](10) NULL,
	[REMOTE_INSPECTION] [nvarchar](10) NULL,
	[REPLICATION_OF_REPORT_CATEGORY2] [nvarchar](100) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


DROP TABLE IF EXISTS [SOURCE__WORKPLAN_IMPORT];
CREATE TABLE [dbo].[SOURCE__WORKPLAN_IMPORT](
import_number							 int,
fiscal_year								 nvarchar  (10),
[TYPE]									 [nvarchar](500),
Administrative_Region					 [nvarchar](500),
IIS_ID									 [nvarchar](500),
MOC_ID									 [nvarchar](500),
MOC_ID_PREFIX							 [nvarchar](500),
COMPANY_NAME							 [nvarchar](500),
ADDRESS_CIVIC							 [nvarchar](500),
POSTALCODE								 [nvarchar](500),
CITY_CIVIC								 [nvarchar](500),
[ZONE]									 [nvarchar](500),
PROV_CIVIC								 [nvarchar](500),
LAT_CIVIC								 [nvarchar](500),
LONG_CIVIC								 [nvarchar](500),
ADDRESS_PHYSICAL						 [nvarchar](500),
CITY_PHYSICAL							 [nvarchar](500),
POSTAL_PHYSICAL							 [nvarchar](500),
PROV_PHYSICAL							 [nvarchar](500),
LAT_PHYSICAL							 [nvarchar](500),
LONG_PHYSICAL							 [nvarchar](500),
ADDRESS_GD								 [nvarchar](500),
CITY_GD									 [nvarchar](500),
POSTAL_GD								 [nvarchar](500),
PROV_GD									 [nvarchar](500),
COUNTRY									 [nvarchar](500),
OUT_OF_COUNTRY_FLAG						 [nvarchar](500),
REGION									 [nvarchar](500),
RISK_CATEGORY							 [nvarchar](500),
[EXPIRY_DATE]							 [nvarchar](500),
LAST_ACTIVITY_DATE						 [nvarchar](500),
LAST_ACTIVITY_TYPE						 [nvarchar](500),
DUE_PRIORITY							 [nvarchar](500),
PROGRAM									 [nvarchar](500),
PLANNED_GC_2018_2019					 [nvarchar](500),
PLANNED_GC_2017_2018					 [nvarchar](500),
PLANNED_FOR_2016_2017					 [nvarchar](500),
PLANNED_LAST_YEAR						 [nvarchar](500),
PLANNED_MOC_2017_2018					 [nvarchar](500),
PLANNED_MOC_2018_2019					 [nvarchar](500),
TYPE_OF_FACILITY						 [nvarchar](500),
FILESTATUS								 [nvarchar](500),
ISSUE_DATE								 [nvarchar](500),
LAST_INSPECTION_DATE					 [nvarchar](500),
HQ_ONLY_FLAG							 [nvarchar](500),
CURRENT_INSPECTOR						 [nvarchar](500),
QUARTER_1								 [nvarchar](500),
QUARTER_2								 [nvarchar](500),
QUARTER_3								 [nvarchar](500),
QUARTER_4								 [nvarchar](500),
CURRENTLY_PLANNED						 [nvarchar](500),
ORIGINAL_INSPECTOR						 [nvarchar](500),
ORIGINALLY_PLANNED						 [nvarchar](500),
IIS_PROFILE_QUALITY_CHECK				 [nvarchar](500),
IIS_ACTIVITY_DATE_1						 [nvarchar](500),
IIS_TYPE_1								 [nvarchar](500),
IIS_CONSIGNMENT_1						 [nvarchar](500),
IIS_PRIMARY_INSPECTOR_1					 [nvarchar](500),
IIS_SECONDARY_INSPECTOR_1				 [nvarchar](500),
IIS_CREATION_DATE_1						 [nvarchar](500),
IIS_QUALITY_CHECK_1						 [nvarchar](500),
IIS_CEP_DATA_1							 [nvarchar](500),
IIS_VIOLATION_LIST_1					 [nvarchar](500),
IIS_VIOLATION_COUNT_1					 [nvarchar](500),
IIS_ACTIVITY_DATE_2						 [nvarchar](500),
IIS_TYPE_2								 [nvarchar](500),
IIS_CONSIGNMENT_2						 [nvarchar](500),
IIS_PRIMARY_INSPECTOR_2					 [nvarchar](500),
IIS_SECONDARY_INSPECTOR_2				 [nvarchar](500),
IIS_CREATION_DATE_2						 [nvarchar](500),
IIS_QUALITY_CHECK_2						 [nvarchar](500),
IIS_CEP_DATA_2							 [nvarchar](500),
IIS_VIOLATION_LIST_2             		 [nvarchar](500),
IIS_VIOLATION_COUNT_2            		 [nvarchar](500),
IIS_ACTIVITY_DATE_3              		 [nvarchar](500),
IIS_TYPE_3                       		 [nvarchar](500),
IIS_CONSIGNMENT_3                		 [nvarchar](500),
IIS_PRIMARY_INSPECTOR_3          		 [nvarchar](500),
IIS_SECONDARY_INSPECTOR_3        		 [nvarchar](500),
IIS_CREATION_DATE_3              		 [nvarchar](500),
IIS_QUALITY_CHECK_3              		 [nvarchar](500),
IIS_CEP_DATA_3                   		 [nvarchar](500),
IIS_VIOLATION_LIST_3             		 [nvarchar](500),
IIS_VIOLATION_COUNT_3            		 [nvarchar](500),
IIS_ACTIVITY_DATE_4              		 [nvarchar](500),
IIS_TYPE_4                       		 [nvarchar](500),
IIS_CONSIGNMENT_4                		 [nvarchar](500),
IIS_PRIMARY_INSPECTOR_4          		 [nvarchar](500),
IIS_SECONDARY_INSPECTOR_4        		 [nvarchar](500),
IIS_CREATION_DATE_4              		 [nvarchar](500),
IIS_QUALITY_CHECK_4              		 [nvarchar](500),
IIS_CEP_DATA_4                   		 [nvarchar](500),
IIS_VIOLATION_LIST_4             		 [nvarchar](500),
IIS_VIOLATION_COUNT_4            		 [nvarchar](500),
IIS_ACTIVITY_DATE_5              		 [nvarchar](500),
IIS_TYPE_5                       		 [nvarchar](500),
IIS_CONSIGNMENT_5                		 [nvarchar](500),
IIS_PRIMARY_INSPECTOR_5          		 [nvarchar](500),
IIS_SECONDARY_INSPECTOR_5        		 [nvarchar](500),
IIS_CREATION_DATE_5              		 [nvarchar](500),
IIS_QUALITY_CHECK_5              		 [nvarchar](500),
IIS_CEP_DATA_5                   		 [nvarchar](500),
IIS_VIOLATION_COUNT_5            		 [nvarchar](500),
IIS_VIOLATION_LIST_5             		 [nvarchar](500),
IIS_ACTIVITY_DATE_6              		 [nvarchar](500),
IIS_TYPE_6                       		 [nvarchar](500),
IIS_CONSIGNMENT_6                		 [nvarchar](500),
IIS_PRIMARY_INSPECTOR_6          		 [nvarchar](500),
IIS_SECONDARY_INSPECTOR_6        		 [nvarchar](500),
IIS_CREATION_DATE_6              		 [nvarchar](500),
IIS_QUALITY_CHECK_6              		 [nvarchar](500),
IIS_CEP_DATA_6                   		 [nvarchar](500),
IIS_VIOLATION_COUNT_6            		 [nvarchar](500),
IIS_VIOLATION_LIST_6             		 [nvarchar](500),
JUSTIFICATION_FOR_NOT_INSPECTING 		 [nvarchar](500),
EXPLANATION                      		 [nvarchar](500),
DATE_MADE_INACTIVE               		 [nvarchar](500),
SITE_STATUS                      		 [nvarchar](500),
SITE_CLOSED_INDICATOR            		 [nvarchar](500),
DELETED_INDICATOR                		 [nvarchar](500),
CLOSED                           		 [nvarchar](500),
YEARS_SINCE_LAST_INSPECTION      		 [nvarchar](500),
TRANSLOAD_FLAG                   		 [nvarchar](500),
CEP_SAMPLE_FLAG                  		 [nvarchar](500),
ALBERTA_HWY                      		 [nvarchar](500),
HUBS_FLAG                        		 [nvarchar](500),
ALBERTA_DROP                     		 [nvarchar](500),
US_DROP                          		 [nvarchar](500),
MOC_ONLY_INDICATOR  					 [nvarchar](500)
) ON [PRIMARY]
GO


DROP TABLE IF EXISTS [dbo].[SOURCE__IIS_EXPORT];
CREATE TABLE [dbo].[SOURCE__IIS_EXPORT] (
    [STAKEHOLDER_ID] NVARCHAR(255),
	[STAKEHOLDER_TYPE_CD] NVARCHAR(50),
    [FILE_STATUS_CD] NVARCHAR(255),
    [INVESTIGATION_IND] NVARCHAR(255),
    [PROSECUTION_IND] NVARCHAR(255),
    [BUSINESS_CATEGORY_CD] NVARCHAR(500),
    [LEGAL_NAME_ENM] NVARCHAR(500),
    [OPERATING_NAME_ENM] NVARCHAR(500),
    [AKA_NAME_ENM] NVARCHAR(500),
    [STREET_NUMBER_NUM] NVARCHAR(255),
    [STREET_NAME_NM] NVARCHAR(255),
    [CITY_TOWN_NAME_NM] NVARCHAR(255),
    [COUNTRY_SUBDIVISION_CD] NVARCHAR(255),
    [POSTAL_CODE_TXT] NVARCHAR(255),
    [PHYS_STREET_NUMBER_NUM] NVARCHAR(255),
    [PHYS_STREET_NAME_NM] NVARCHAR(255),
    [PHYS_CITY_TOWN_NAME_NM] NVARCHAR(255),
    [PHYS_COUNTRY_CD] NVARCHAR(255),
    [PHYS_COUNTRY_ENM] NVARCHAR(255),
    [PHYS_COUNTRY_FNM] NVARCHAR(255),
    [PHYS_COUNTRY_SUBDIVISION_CD] NVARCHAR(255),
    [PHYS_COUNTRY_SUBDIVISION_ENM] NVARCHAR(255),
    [PHYS_COUNTRY_SUBDIVISION_FNM] NVARCHAR(255),
    [PHYS_POSTAL_CODE_TXT] NVARCHAR(255),
    [USER_CONTACT] NVARCHAR(255),
    [LAST_ACTIVITY_DATE] NVARCHAR(255),
    [TRANSPORT_MODE_ETXT] NVARCHAR(2000),
    [TRANSPORT_MODE_FTXT] NVARCHAR(2000),
    [TRANSPORT_MODE_CD] NVARCHAR(2000),
    [DG_CLASS] NVARCHAR(4000),
    [UN_NUMBER] NVARCHAR(4000),
    [UNIT_SUITE_NUM] NVARCHAR(255),
    [LATITUDE_DEGREE_NBR] NVARCHAR(255),
    [LATITUDE_MINUTE_NBR] NVARCHAR(255),
    [LONGITUDE_DEGREE_NBR] NVARCHAR(255),
    [LONGITUDE_MINUTE_NBR] NVARCHAR(255),
    [PHYS_LATITUDE_DEGREE_NBR] NVARCHAR(255),
    [PHYS_LATITUDE_MINUTE_NBR] NVARCHAR(255),
    [PHYS_LONGITUDE_DEGREE_NBR] NVARCHAR(255),
    [PHYS_LONGITUDE_MINUTE_NBR] NVARCHAR(255),
    [CONTACT_PHONE] NVARCHAR(255),
    [CONTACT_BUSINESS_PHONE] NVARCHAR(255),
    [CONTACT_EMAIL] NVARCHAR(255),
    [CONTACT_TFH] NVARCHAR(255),
    [CONTACT_TXT] NVARCHAR(255)
) ON [PRIMARY]
GO


DROP TABLE IF EXISTS [dbo].[SOURCE__FISCAL_YEAR];
CREATE TABLE [SOURCE__FISCAL_YEAR] (
    [createdby] UNIQUEIDENTIFIER,
    [createdbyname] NVARCHAR(200),
    [createdbyyominame] NVARCHAR(200),
    [createdon] DATETIME,
    [createdonbehalfby] UNIQUEIDENTIFIER,
    [createdonbehalfbyname] NVARCHAR(200),
    [createdonbehalfbyyominame] NVARCHAR(200),
    [importsequencenumber] INT,
    [modifiedby] UNIQUEIDENTIFIER,
    [modifiedbyname] NVARCHAR(200),
    [modifiedbyyominame] NVARCHAR(200),
    [modifiedon] DATETIME,
    [modifiedonbehalfby] UNIQUEIDENTIFIER,
    [modifiedonbehalfbyname] NVARCHAR(200),
    [modifiedonbehalfbyyominame] NVARCHAR(200),
    [overriddencreatedon] DATETIME,
    [ownerid] UNIQUEIDENTIFIER,
    [owneridname] NVARCHAR(200),
    [owneridtype] NVARCHAR(64),
    [owneridyominame] NVARCHAR(200),
    [owningbusinessunit] UNIQUEIDENTIFIER,
    [owningteam] UNIQUEIDENTIFIER,
    [owninguser] UNIQUEIDENTIFIER,
    [statecode] INT,
    [statecodename] NVARCHAR(255),
    [statuscode] INT,
    [statuscodename] NVARCHAR(255),
    [tc_fiscalend] DATETIME,
    [tc_fiscalstart] DATETIME,
    [tc_fiscalyearlonglbl] NVARCHAR(100),
    [tc_fiscalyearnum] NVARCHAR(100),
    [tc_iscurrentfiscalyear] BIT,
    [tc_iscurrentfiscalyearname] NVARCHAR(255),
    [tc_name] NVARCHAR(100),
    [tc_tcfiscalyearid] UNIQUEIDENTIFIER,
    [tc_todaysdate] DATETIME,
    [timezoneruleversionnumber] INT,
    [utcconversiontimezonecode] INT,
    [versionnumber] BIGINT
)  ON [PRIMARY]
GO


DROP TABLE IF EXISTS [dbo].[SOURCE__FISCAL_QUARTER];
CREATE TABLE [[SOURCE__FISCAL_QUARTER] (
    [createdby] UNIQUEIDENTIFIER,
    [createdbyname] NVARCHAR(200),
    [createdbyyominame] NVARCHAR(200),
    [createdon] DATETIME,
    [createdonbehalfby] UNIQUEIDENTIFIER,
    [createdonbehalfbyname] NVARCHAR(200),
    [createdonbehalfbyyominame] NVARCHAR(200),
    [importsequencenumber] INT,
    [modifiedby] UNIQUEIDENTIFIER,
    [modifiedbyname] NVARCHAR(200),
    [modifiedbyyominame] NVARCHAR(200),
    [modifiedon] DATETIME,
    [modifiedonbehalfby] UNIQUEIDENTIFIER,
    [modifiedonbehalfbyname] NVARCHAR(200),
    [modifiedonbehalfbyyominame] NVARCHAR(200),
    [overriddencreatedon] DATETIME,
    [ownerid] UNIQUEIDENTIFIER,
    [owneridname] NVARCHAR(200),
    [owneridtype] NVARCHAR(64),
    [owneridyominame] NVARCHAR(200),
    [owningbusinessunit] UNIQUEIDENTIFIER,
    [owningteam] UNIQUEIDENTIFIER,
    [owninguser] UNIQUEIDENTIFIER,
    [statecode] INT,
    [statecodename] NVARCHAR(255),
    [statuscode] INT,
    [statuscodename] NVARCHAR(255),
    [tc_fiscalquarterlbl] NVARCHAR(100),
    [tc_fiscalquarterlonglbl] NVARCHAR(100),
    [tc_fiscalquarternum] INT,
    [tc_name] NVARCHAR(100),
    [tc_quarterend] DATETIME,
    [tc_quarterstart] DATETIME,
    [tc_tcfiscalquarterid] UNIQUEIDENTIFIER,
    [tc_tcfiscalyearid] UNIQUEIDENTIFIER,
    [tc_tcfiscalyearidname] NVARCHAR(100),
    [timezoneruleversionnumber] INT,
    [utcconversiontimezonecode] INT,
    [versionnumber] BIGINT
)  ON [PRIMARY]
GO


DROP TABLE IF EXISTS [dbo].[[SOURCE__SYSTEM_USER];
CREATE TABLE [[SOURCE__SYSTEM_USER] (
    [accessmode] INT,
    [accessmodename] NVARCHAR(255),
    [address1_addressid] UNIQUEIDENTIFIER,
    [address1_addresstypecode] INT,
    [address1_addresstypecodename] NVARCHAR(255),
    [address1_city] NVARCHAR(128),
    [address1_composite] NTEXT,
    [address1_country] NVARCHAR(128),
    [address1_county] NVARCHAR(128),
    [address1_fax] NVARCHAR(64),
    [address1_latitude] FLOAT,
    [address1_line1] NVARCHAR(1024),
    [address1_line2] NVARCHAR(1024),
    [address1_line3] NVARCHAR(1024),
    [address1_longitude] FLOAT,
    [address1_name] NVARCHAR(100),
    [address1_postalcode] NVARCHAR(40),
    [address1_postofficebox] NVARCHAR(40),
    [address1_shippingmethodcode] INT,
    [address1_shippingmethodcodename] NVARCHAR(255),
    [address1_stateorprovince] NVARCHAR(128),
    [address1_telephone1] NVARCHAR(64),
    [address1_telephone2] NVARCHAR(50),
    [address1_telephone3] NVARCHAR(50),
    [address1_upszone] NVARCHAR(4),
    [address1_utcoffset] INT,
    [address2_addressid] UNIQUEIDENTIFIER,
    [address2_addresstypecode] INT,
    [address2_addresstypecodename] NVARCHAR(255),
    [address2_city] NVARCHAR(128),
    [address2_composite] NTEXT,
    [address2_country] NVARCHAR(128),
    [address2_county] NVARCHAR(128),
    [address2_fax] NVARCHAR(50),
    [address2_latitude] FLOAT,
    [address2_line1] NVARCHAR(1024),
    [address2_line2] NVARCHAR(1024),
    [address2_line3] NVARCHAR(1024),
    [address2_longitude] FLOAT,
    [address2_name] NVARCHAR(100),
    [address2_postalcode] NVARCHAR(40),
    [address2_postofficebox] NVARCHAR(40),
    [address2_shippingmethodcode] INT,
    [address2_shippingmethodcodename] NVARCHAR(255),
    [address2_stateorprovince] NVARCHAR(128),
    [address2_telephone1] NVARCHAR(50),
    [address2_telephone2] NVARCHAR(50),
    [address2_telephone3] NVARCHAR(50),
    [address2_upszone] NVARCHAR(4),
    [address2_utcoffset] INT,
    [applicationid] UNIQUEIDENTIFIER,
    [applicationiduri] NVARCHAR(1024),
    [azureactivedirectoryobjectid] UNIQUEIDENTIFIER,
    [businessunitid] UNIQUEIDENTIFIER,
    [businessunitidname] NVARCHAR(160),
    [calendarid] UNIQUEIDENTIFIER,
    [caltype] INT,
    [caltypename] NVARCHAR(255),
    [createdby] UNIQUEIDENTIFIER,
    [createdbyname] NVARCHAR(200),
    [createdbyyominame] NVARCHAR(200),
    [createdon] DATETIME,
    [createdonbehalfby] UNIQUEIDENTIFIER,
    [createdonbehalfbyname] NVARCHAR(200),
    [createdonbehalfbyyominame] NVARCHAR(200),
    [defaultfilterspopulated] BIT,
    [defaultmailbox] UNIQUEIDENTIFIER,
    [defaultmailboxname] NVARCHAR(200),
    [defaultodbfoldername] NVARCHAR(200),
    [disabledreason] NVARCHAR(500),
    [displayinserviceviews] BIT,
    [displayinserviceviewsname] NVARCHAR(255),
    [domainname] NVARCHAR(1024),
    [emailrouteraccessapproval] INT,
    [emailrouteraccessapprovalname] NVARCHAR(255),
    [employeeid] NVARCHAR(100),
    [entityimage] IMAGE,
    [entityimage_timestamp] BIGINT,
    [entityimage_url] NVARCHAR(200),
    [entityimageid] UNIQUEIDENTIFIER,
    [exchangerate] NUMERIC(38, 10),
    [firstname] NVARCHAR(256),
    [fullname] NVARCHAR(200),
    [governmentid] NVARCHAR(100),
    [homephone] NVARCHAR(50),
    [identityid] INT,
    [importsequencenumber] INT,
    [incomingemaildeliverymethod] INT,
    [incomingemaildeliverymethodname] NVARCHAR(255),
    [internalemailaddress] NVARCHAR(100),
    [invitestatuscode] INT,
    [invitestatuscodename] NVARCHAR(255),
    [isdisabled] BIT,
    [isdisabledname] NVARCHAR(255),
    [isemailaddressapprovedbyo365admin] BIT,
    [isintegrationuser] BIT,
    [isintegrationusername] NVARCHAR(255),
    [islicensed] BIT,
    [islicensedname] NVARCHAR(255),
    [issyncwithdirectory] BIT,
    [jobtitle] NVARCHAR(100),
    [lastname] NVARCHAR(256),
    [middlename] NVARCHAR(50),
    [mobilealertemail] NVARCHAR(100),
    [mobileofflineprofileid] UNIQUEIDENTIFIER,
    [mobileofflineprofileidname] NVARCHAR(255),
    [mobilephone] NVARCHAR(64),
    [modifiedby] UNIQUEIDENTIFIER,
    [modifiedbyname] NVARCHAR(200),
    [modifiedbyyominame] NVARCHAR(200),
    [modifiedon] DATETIME,
    [modifiedonbehalfby] UNIQUEIDENTIFIER,
    [modifiedonbehalfbyname] NVARCHAR(200),
    [modifiedonbehalfbyyominame] NVARCHAR(200),
    [msdyn_gdproptout] BIT,
    [msdyn_gdproptoutname] NVARCHAR(255),
    [nickname] NVARCHAR(50),
    [organizationid] UNIQUEIDENTIFIER,
    [organizationidname] NVARCHAR(100),
    [outgoingemaildeliverymethod] INT,
    [outgoingemaildeliverymethodname] NVARCHAR(255),
    [overriddencreatedon] DATETIME,
    [parentsystemuserid] UNIQUEIDENTIFIER,
    [parentsystemuseridname] NVARCHAR(200),
    [parentsystemuseridyominame] NVARCHAR(200),
    [passporthi] INT,
    [passportlo] INT,
    [personalemailaddress] NVARCHAR(100),
    [photourl] NVARCHAR(200),
    [positionid] UNIQUEIDENTIFIER,
    [positionidname] NVARCHAR(100),
    [preferredaddresscode] INT,
    [preferredaddresscodename] NVARCHAR(255),
    [preferredemailcode] INT,
    [preferredemailcodename] NVARCHAR(255),
    [preferredphonecode] INT,
    [preferredphonecodename] NVARCHAR(255),
    [processid] UNIQUEIDENTIFIER,
    [queueid] UNIQUEIDENTIFIER,
    [queueidname] NVARCHAR(400),
    [salutation] NVARCHAR(20),
    [setupuser] BIT,
    [setupusername] NVARCHAR(255),
    [sharepointemailaddress] NVARCHAR(1024),
    [siteid] UNIQUEIDENTIFIER,
    [siteidname] NVARCHAR(160),
    [skills] NVARCHAR(100),
    [stageid] UNIQUEIDENTIFIER,
    [systemuserid] UNIQUEIDENTIFIER,
    [territoryid] UNIQUEIDENTIFIER,
    [territoryidname] NVARCHAR(200),
    [timezoneruleversionnumber] INT,
    [title] NVARCHAR(128),
    [transactioncurrencyid] UNIQUEIDENTIFIER,
    [transactioncurrencyidname] NVARCHAR(100),
    [traversedpath] NVARCHAR(1250),
    [userlicensetype] INT,
    [userpuid] NVARCHAR(100),
    [utcconversiontimezonecode] INT,
    [versionnumber] BIGINT,
    [windowsliveid] NVARCHAR(1024),
    [yammeremailaddress] NVARCHAR(200),
    [yammeruserid] NVARCHAR(128),
    [yomifirstname] NVARCHAR(64),
    [yomifullname] NVARCHAR(200),
    [yomilastname] NVARCHAR(64),
    [yomimiddlename] NVARCHAR(50)
) ON [PRIMARY]
GO

DROP TABLE [dbo].[SOURCE__IIS_INSPECTORS];
CREATE TABLE [dbo].[SOURCE__IIS_INSPECTORS](
	[USER_ID] [nvarchar](255) NULL,
	[First Name] [nvarchar](255) NULL,
	[Last Name] [nvarchar](255) NULL,
	[Fullname] [nvarchar](255) NULL,
	[Account_name] [nvarchar](255) NULL,
	[BADGE] [nvarchar](255) NULL,
	[RIN] [nvarchar](255) NULL,
	[RegionCrmId] [nvarchar](255) NULL,
	[Region] [nvarchar](255) NULL,
	[RegionEnm] [nvarchar](255) NULL,
	[RegionFnm] [nvarchar](255) NULL
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[20_LEGISLATION_MATCHING]    Script Date: 4/20/2021 10:25:08 PM ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[[SOURCE__LEGISLATION_MATCHING]') AND type in (N'U'))
DROP TABLE [dbo].[[SOURCE__LEGISLATION_MATCHING]
GO

CREATE TABLE [dbo].[[SOURCE__LEGISLATION_MATCHING](
	[LegislationId] [nvarchar](255) NULL,
	[Parent Legislation] [nvarchar](255) NULL,
	[Name] [nvarchar](4000) NULL,
	[English Text] [nvarchar](4000) NULL,
	[French Text] [nvarchar](4000) NULL,
	[Label] [nvarchar](255) NULL,
	[Legislation Source] [nvarchar](255) NULL,
	[Legislation Type] [nvarchar](255) NULL,
	[Last Amended Dte] [nvarchar](255) NULL,
	[Enabling Provision] [nvarchar](255) NULL,
	[Order] [nvarchar](255) NULL,
	[Modified Label] [nvarchar](255) NULL,
	[Violation Display Text EN] [nvarchar](4000) NULL,
	[Violation Display Text FR] [nvarchar](4000) NULL,
	[Violation Display Text EN2] [nvarchar](4000) NULL,
	[Violation Display Text FR2] [nvarchar](4000) NULL,
	[VIOLATION_CD] [numeric](18, 0) NULL,
	[VIOLATION_REFERENCE_CD] [nvarchar](20) NULL
) ON [PRIMARY]
GO

