DROP TABLE IF EXISTS [19_IIS_INSPECTIONS];

CREATE TABLE [19_IIS_INSPECTIONS]
(
	[MONTH] int
	,[YEAR]	int	
	,FILE_NUMBER_NUM nvarchar (200)
	,FILE_STATUS_ETXT	varchar	(50)
	,FILE_STATUS_FTXT	varchar	(50)
	,ACTIVITY_TYPE_ENM	varchar	(250)
	,ACTIVITY_TYPE_FNM	varchar	(250)
	,ACTIVITY_DATE_DTE	datetime	
	,ACTIVITY_ID	numeric	
	,STAKEHOLDER_ID	numeric	
	,id	uniqueidentifier	
	,ovs_iisid	nvarchar	(50)
	,ACTIVITY_TYPE_CD	varchar	(20)
	,INSPECTION_REASON_ETXT	varchar	(250)
	,INSPECTION_REASON_FTXT	varchar	(250)
	,PRIMARY_INSPECTOR	nvarchar	(200)
	,PRIMARY_INSPECTOR_ID	numeric	
	,PRIMARY_INSPECTOR_BOOKABLE_RESOURCE_ID	uniqueidentifier	
	,SECONDARY_INSPECTOR	nvarchar (200)
	,SECONDARY_INSPECTOR_ID	numeric	
	,SECONDARY_INSPECTOR_BOOKABLE_RESOURCE_ID	uniqueidentifier
);

INSERT INTO [19_IIS_INSPECTIONS]

SELECT
MONTH(ACTIVITY_DATE_DTE) [MONTH],
YEAR(ACTIVITY_DATE_DTE) [YEAR],
*
FROM 
(
	SELECT 
	YD095.FILE_NUMBER_NUM, 
	TD001.FILE_STATUS_ETXT, 
	TD001.FILE_STATUS_FTXT, 
	TD045.ACTIVITY_TYPE_ENM, 
	TD045.ACTIVITY_TYPE_FNM,
	CONVERT(datetime, YD040.ACTIVITY_DATE_DTE) ACTIVITY_DATE_DTE,
	YD040.ACTIVITY_ID, 
	YD040.STAKEHOLDER_ID, 
	null id,--ACCOUNTS.id,
	null ovs_iisid,--ACCOUNTS.[ovs_iisid],
	TD045.ACTIVITY_TYPE_CD, 
	TD038.INSPECTION_REASON_ETXT, 
	TD038.INSPECTION_REASON_FTXT,
	PRIMARY_INSPECTOR.name PRIMARY_INSPECTOR,
	PRIMARY_INSPECTOR.STAKEHOLDER_ID PRIMARY_INSPECTOR_ID, 
	PRIMARY_INSPECTOR.bookableresourceid PRIMARY_INSPECTOR_BOOKABLE_RESOURCE_ID,
	SECONDARY_INSPECTOR.name SECONDARY_INSPECTOR,
	SECONDARY_INSPECTOR.STAKEHOLDER_ID SECONDARY_INSPECTOR_ID,
	SECONDARY_INSPECTOR.bookableresourceid SECONDARY_INSPECTOR_BOOKABLE_RESOURCE_ID
	FROM YD040_ACTIVITY YD040
	INNER JOIN YD095_STAKEHOLDER_FILE YD095 ON  YD040.FILE_NUMBER_NUM = YD095.FILE_NUMBER_NUM  
	INNER JOIN YD101_FILE_ACTIVITY_TYPE YD101 ON YD101.FILE_NUMBER_NUM = YD095.FILE_NUMBER_NUM AND YD101.DATE_DELETED_DTE IS NULL
	INNER JOIN TD045_ACTIVITY_TYPE TD045 ON YD101.ACTIVITY_TYPE_CD = TD045.ACTIVITY_TYPE_CD 
	INNER JOIN TD001_FILE_STATUS TD001 ON YD095.FILE_STATUS_CD = TD001.FILE_STATUS_CD
	LEFT JOIN YD041_INSPECTION YD041 ON YD040.ACTIVITY_ID = YD041.ACTIVITY_ID 
	LEFT JOIN TD038_INSPECTION_REASON TD038 ON YD041.INSPECTION_REASON_CD = TD038.INSPECTION_REASON_CD 
    
	LEFT JOIN
	(
		SELECT YD048.ACTIVITY_ID,
		YD048.STAKEHOLDER_ID
		,name
		,BR.bookableresourceid
		FROM YD048_ACTIVITY_ASSIGNMENT YD048 
		JOIN YD083_INDIVIDUAL_INFORMATION YD083 ON  YD048.STAKEHOLDER_ID = YD083.STAKEHOLDER_ID 
		JOIN [dbo].[bookableresource] BR ON UPPER(TRIM(CONCAT(CONCAT(YD083.STAKEHOLDER_NAME_FIRST_NM, ' '), YD083.STAKEHOLDER_NAME_FAMILY_NM))) = UPPER([dbo].[ReplaceASCII](name))
		WHERE YD083.DATE_DELETED_DTE IS NULL AND YD048.DATE_DELETED_DTE IS NULL AND ASSIGN_ROLE_CD = '1'
	) PRIMARY_INSPECTOR ON PRIMARY_INSPECTOR.ACTIVITY_ID = YD040.ACTIVITY_ID
    
	LEFT JOIN
	(
		SELECT YD048.ACTIVITY_ID,
		YD048.STAKEHOLDER_ID
		,name
		,BR.bookableresourceid
		FROM YD048_ACTIVITY_ASSIGNMENT YD048 
		JOIN YD083_INDIVIDUAL_INFORMATION YD083 ON  YD048.STAKEHOLDER_ID = YD083.STAKEHOLDER_ID 
		JOIN [dbo].[bookableresource] BR ON UPPER(TRIM(CONCAT(CONCAT(YD083.STAKEHOLDER_NAME_FIRST_NM, ' '), YD083.STAKEHOLDER_NAME_FAMILY_NM))) = UPPER([dbo].[ReplaceASCII](name))
		WHERE YD083.DATE_DELETED_DTE IS NULL AND YD048.DATE_DELETED_DTE IS NULL AND ASSIGN_ROLE_CD = '2'
	) SECONDARY_INSPECTOR ON SECONDARY_INSPECTOR.ACTIVITY_ID = YD040.ACTIVITY_ID
    
	--JOIN [dbo].[04_ACCOUNT] ACCOUNTS ON ACCOUNTS.ovs_iisid = YD040.STAKEHOLDER_ID

	WHERE 
	YD040.DATE_DELETED_DTE IS NULL AND 
	YD095.DATE_DELETED_DTE IS NULL AND 
	YD041.DATE_DELETED_DTE IS NULL AND 
	YD101.DATE_DELETED_DTE IS NULL 
	AND TD045.ACTIVITY_TYPE_PARENT_CD IS NULL AND TD045.DATE_DELETED_DTE IS NULL
	GROUP BY 
	YD095.FILE_NUMBER_NUM, 
	TD001.FILE_STATUS_ETXT, 
	TD001.FILE_STATUS_FTXT, 
	TD045.ACTIVITY_TYPE_ENM, 
	TD045.ACTIVITY_TYPE_FNM, 
	YD040.INSPECTION_DATE_DTE, 
	YD040.ACTIVITY_ID, 
	YD040.STAKEHOLDER_ID, 
	--ACCOUNTS.id,
	--ACCOUNTS.ovs_iisid,
	TD045.ACTIVITY_TYPE_CD, 
	TD038.INSPECTION_REASON_ETXT, 
	TD038.INSPECTION_REASON_FTXT,
	YD040.ACTIVITY_DATE_DTE,
	PRIMARY_INSPECTOR.name,
	PRIMARY_INSPECTOR.STAKEHOLDER_ID, 
	PRIMARY_INSPECTOR.bookableresourceid,
	SECONDARY_INSPECTOR.name,
	SECONDARY_INSPECTOR.STAKEHOLDER_ID,
	SECONDARY_INSPECTOR.bookableresourceid
			
) T


--connect the IIS Inspections to the Accounts in ROM
UPDATE [19_IIS_INSPECTIONS]
SET 
id = ACCOUNTS.Id
,ovs_iisid = STAKEHOLDER_ID
FROM [19_IIS_INSPECTIONS]
JOIN [dbo].[04_ACCOUNT] ACCOUNTS ON ACCOUNTS.ovs_iisid = STAKEHOLDER_ID

SELECT * FROM [04_ACCOUNT];