--TRUNCATE TABLE "TD070_VIOLATION";
--TRUNCATE TABLE "TD071_ACT_REFERENCE";
--TRUNCATE TABLE "YD020_INSPECTION_VIOLATION";
--TRUNCATE TABLE "YD021_MOCLIST";
--TRUNCATE TABLE "YD023_VIOL_ENFORCEMENT_ACTION";
--TRUNCATE TABLE "YD030_STAKEHOLDER_HOTI";
--TRUNCATE TABLE "YD032_STAKEHOLDER_MODE_PROFILE";
--TRUNCATE TABLE "YD033_STAKEHOLDER_CLASS_PROFIL";
--TRUNCATE TABLE "YD034_STAKEHOLDER_BUSINESS";
--TRUNCATE TABLE "YD039_ACTIVITY_ADDRESS";
--TRUNCATE TABLE "YD040_ACTIVITY";
--TRUNCATE TABLE "YD041_INSPECTION";
--TRUNCATE TABLE "YD042_SITE_VISIT";
--TRUNCATE TABLE "YD048_ACTIVITY_ASSIGNMENT";
--TRUNCATE TABLE "YD070_STAKEHOLDER";
--TRUNCATE TABLE "YD074_INSPECTOR";
--TRUNCATE TABLE "YD075_INDIVIDUAL";
--TRUNCATE TABLE "YD082_INSPECTION_VIOLATION";
--TRUNCATE TABLE "YD083_INDIVIDUAL_INFORMATION";
--TRUNCATE TABLE "YD091_STAKEHOLDER_CONTACT";
--TRUNCATE TABLE "YD092_STAKEHOLDER_ORG_PERS";
--TRUNCATE TABLE "YD093_STAKEHOLDER_ORG_NAME";
--TRUNCATE TABLE "YD095_STAKEHOLDER_FILE";
--TRUNCATE TABLE "YD099_ACTIVITY_SITE_CONTACT";
--TRUNCATE TABLE "YD100_ACTIVITY_REPORT";
--TRUNCATE TABLE "YD101_FILE_ACTIVITY_TYPE";


SELECT 'TD070_VIOLATION', COUNT(*) COUNT_OF FROM [dbo]."TD070_VIOLATION" UNION
SELECT 'TD071_ACT_REFERENCE', COUNT(*) COUNT_OF FROM [dbo]."TD071_ACT_REFERENCE" UNION
SELECT 'YD020_INSPECTION_VIOLATION', COUNT(*) COUNT_OF FROM [dbo]."YD020_INSPECTION_VIOLATION" UNION
SELECT 'YD021_MOCLIST', COUNT(*) COUNT_OF FROM [dbo]."YD021_MOCLIST" UNION
SELECT 'YD023_VIOL_ENFORCEMENT_ACTION', COUNT(*) COUNT_OF FROM [dbo]."YD023_VIOL_ENFORCEMENT_ACTION" UNION
SELECT 'YD030_STAKEHOLDER_HOTI', COUNT(*) COUNT_OF FROM [dbo]."YD030_STAKEHOLDER_HOTI" UNION
SELECT 'YD032_STAKEHOLDER_MODE_PROFILE', COUNT(*) COUNT_OF FROM [dbo]."YD032_STAKEHOLDER_MODE_PROFILE" UNION
SELECT 'YD033_STAKEHOLDER_CLASS_PROFIL', COUNT(*) COUNT_OF FROM [dbo]."YD033_STAKEHOLDER_CLASS_PROFIL" UNION
SELECT 'YD034_STAKEHOLDER_BUSINESS', COUNT(*) COUNT_OF FROM [dbo]."YD034_STAKEHOLDER_BUSINESS" UNION
SELECT 'YD039_ACTIVITY_ADDRESS', COUNT(*) COUNT_OF FROM [dbo]."YD039_ACTIVITY_ADDRESS" UNION
SELECT 'YD040_ACTIVITY', COUNT(*) COUNT_OF FROM [dbo]."YD040_ACTIVITY" UNION
SELECT 'YD041_INSPECTION', COUNT(*) COUNT_OF FROM [dbo]."YD041_INSPECTION" UNION
SELECT 'YD042_SITE_VISIT', COUNT(*) COUNT_OF FROM [dbo]."YD042_SITE_VISIT" UNION
SELECT 'YD048_ACTIVITY_ASSIGNMENT', COUNT(*) COUNT_OF FROM [dbo]."YD048_ACTIVITY_ASSIGNMENT" UNION
SELECT 'YD070_STAKEHOLDER', COUNT(*) COUNT_OF FROM [dbo]."YD070_STAKEHOLDER" UNION
SELECT 'YD074_INSPECTOR', COUNT(*) COUNT_OF FROM [dbo]."YD074_INSPECTOR" UNION
SELECT 'YD075_INDIVIDUAL', COUNT(*) COUNT_OF FROM [dbo]."YD075_INDIVIDUAL" UNION
SELECT 'YD082_INSPECTION_VIOLATION', COUNT(*) COUNT_OF FROM [dbo]."YD082_INSPECTION_VIOLATION" UNION
SELECT 'YD083_INDIVIDUAL_INFORMATION', COUNT(*) COUNT_OF FROM [dbo]."YD083_INDIVIDUAL_INFORMATION" UNION
SELECT 'YD091_STAKEHOLDER_CONTACT', COUNT(*) COUNT_OF FROM [dbo]."YD091_STAKEHOLDER_CONTACT" UNION
SELECT 'YD092_STAKEHOLDER_ORG_PERS', COUNT(*) COUNT_OF FROM [dbo]."YD092_STAKEHOLDER_ORG_PERS" UNION
SELECT 'YD093_STAKEHOLDER_ORG_NAME', COUNT(*) COUNT_OF FROM [dbo]."YD093_STAKEHOLDER_ORG_NAME" UNION
SELECT 'YD095_STAKEHOLDER_FILE', COUNT(*) COUNT_OF FROM [dbo]."YD095_STAKEHOLDER_FILE" UNION
SELECT 'YD099_ACTIVITY_SITE_CONTACT', COUNT(*) COUNT_OF FROM [dbo]."YD099_ACTIVITY_SITE_CONTACT" UNION
SELECT 'YD100_ACTIVITY_REPORT', COUNT(*) COUNT_OF FROM [dbo]."YD100_ACTIVITY_REPORT" UNION
SELECT 'YD101_FILE_ACTIVITY_TYPE', COUNT(*) COUNT_OF FROM [dbo]."YD101_FILE_ACTIVITY_TYPE";

SELECT '09_WORKPLAN_IMPORT', COUNT(*) COUNT_OF FROM [dbo]."09_WORKPLAN_IMPORT";
