UPDATE [dbo].[10_IIS_EXPORT]
SET STREET_NUMBER_NUM = null
WHERE STREET_NUMBER_NUM = '';

UPDATE [dbo].[10_IIS_EXPORT]
SET [PHYS_COUNTRY_CD] = null
WHERE [PHYS_COUNTRY_CD] = '';

UPDATE [dbo].[09_WORKPLAN_IMPORT]
SET [MOC_ID] = null
WHERE [MOC_ID] = '';