//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmWebApiEarlyBoundGenerator {
    
    
    // <summary>
    // what type of question control to render on the ui for this question
    // </summary>
    public enum qm_questionresponsetypecd {
        
        Text = 930840000,
        
        Radio = 930840001,
        
        Select = 930840002,
        
        Number = 930840003,
        
        Image = 930840004,
    }
}
