//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TC.Legislation.EarlyBound {
    
    
    public enum qm_QuestionTypeCd {
        
        Text = 930840002,
        
        Radio = 930840000,
        
        Select = 930840001,
        
        Number = 930840004,
        
        Image = 930840003,
    }
}
