//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmWebApiEarlyBoundGenerator {
    
    
    // <summary>
    // Status of the Question Validation Rule
    //Statut de l'élément Question Validation Rule
    // </summary>
    public enum qm_syquestionvalidationrule_statecode {
        
        Active = 0,
        
        Inactive = 1,
    }
}
