//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TC.Legislation.EarlyBound {
    
    
    // <summary>
    // Reason for the status of the Dependency Group Item
    //Raison du statut de l'élément Dependency Group Item
    // </summary>
    public enum qm_sydependencygroupitem_statuscode {
        
        Active = 1,
        
        Inactive = 2,
    }
}
