//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TC.Legislation.EarlyBound {
    
    
    // <summary>
    // Status of the Template
    //Statut de l'élément Template
    // </summary>
    public enum qm_sytemplate_statecode {
        
        Active = 0,
        
        Inactive = 1,
    }
}
