//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmWebApiEarlyBoundGenerator {
    
    
    // <summary>
    // Reason for the status of the Validation Rule Type
    //Raison du statut de l'élément Validation Rule Type
    // </summary>
    public enum qm_TYValidationruletype_statuscode {
        
        Active = 1,
        
        Inactive = 2,
    }
}
