DELETE FROM SSIS_RegulatedEntityErrors;
DELETE FROM SSIS_SiteErrors;
DELETE FROM SSIS_WorkOrderErrors;
DELETE FROM CRM__BOOKABLERESOURCE;
DELETE FROM CRM__BUSINESSUNIT;
DELETE FROM CRM__PRICELEVEL;
DELETE FROM CRM__SYSTEMUSER;
DELETE FROM CRM__TEAM;
DELETE FROM STAGING__ACCOUNT;
DELETE FROM STAGING__accountclass;
DELETE FROM STAGING__BOOKABLE_RESOURCE;
DELETE FROM STAGING__BOOKABLE_RESOURCE_CATEGORIES;
DELETE FROM STAGING__BOOKABLE_RESOURCE_CATEGORY_ASSN;
DELETE FROM STAGING__COC;
DELETE FROM STAGING__CONTACT;
DELETE FROM STAGING__ENVIRONMENT_SETTINGS;
DELETE FROM STAGING__EQUIPMENT_TYPE;
DELETE FROM STAGING__OVERSIGHTTYPE;
DELETE FROM STAGING__TERRITORY;
DELETE FROM STAGING__tylegislation;
DELETE FROM STAGING__tylegislationsource;
DELETE FROM STAGING__tylegislationtype;
DELETE FROM STAGING__TYRATIONAL;
DELETE FROM STAGING__UNPLANNED_FORECAST;
DELETE FROM STAGING__VIOLATIONS;
DELETE FROM STAGING__WORK_ORDERS;
DELETE FROM STAGING__WORKORDERTYPE;
DELETE FROM SOURCE__DATA_CONSOLIDATION;
DELETE FROM [dbo].[ERRORS__COC];
DELETE FROM [dbo].[ERRORs__BUSINESSUNIT];

--LOAD ERRORS
SELECT COUNT(*)	SSIS_RegulatedEntityErrors					FROM SSIS_RegulatedEntityErrors;
SELECT COUNT(*)	SSIS_SiteErrors								FROM SSIS_SiteErrors;
SELECT COUNT(*)	SSIS_WorkOrderErrors						FROM SSIS_WorkOrderErrors;
-- CRM ORGANIZATION DATA
SELECT COUNT(*)	CRM__BOOKABLERESOURCE						FROM CRM__BOOKABLERESOURCE;
SELECT COUNT(*)	CRM__BUSINESSUNIT							FROM CRM__BUSINESSUNIT;
SELECT COUNT(*)	CRM__PRICELEVEL								FROM CRM__PRICELEVEL;
SELECT COUNT(*)	CRM__SYSTEMUSER								FROM CRM__SYSTEMUSER;
SELECT COUNT(*)	CRM__TEAM									FROM CRM__TEAM;
--STAGING DATA
SELECT COUNT(*)	STAGING__ACCOUNT							FROM STAGING__ACCOUNT;
SELECT COUNT(*)	STAGING__accountclass						FROM STAGING__accountclass;
SELECT COUNT(*)	STAGING__BOOKABLE_RESOURCE					FROM STAGING__BOOKABLE_RESOURCE;
SELECT COUNT(*)	STAGING__BOOKABLE_RESOURCE_CATEGORIES		FROM STAGING__BOOKABLE_RESOURCE_CATEGORIES;
SELECT COUNT(*)	STAGING__BOOKABLE_RESOURCE_CATEGORY_ASSN	FROM STAGING__BOOKABLE_RESOURCE_CATEGORY_ASSN;
SELECT COUNT(*)	STAGING__COC								FROM STAGING__COC;
SELECT COUNT(*)	STAGING__CONTACT							FROM STAGING__CONTACT;
SELECT COUNT(*)	STAGING__ENVIRONMENT_SETTINGS				FROM STAGING__ENVIRONMENT_SETTINGS;
SELECT COUNT(*)	STAGING__EQUIPMENT_TYPE						FROM STAGING__EQUIPMENT_TYPE;
SELECT COUNT(*)	STAGING__OVERSIGHTTYPE						FROM STAGING__OVERSIGHTTYPE;
SELECT COUNT(*)	STAGING__TERRITORY							FROM STAGING__TERRITORY;
SELECT COUNT(*)	STAGING__tylegislation						FROM STAGING__tylegislation;
SELECT COUNT(*)	STAGING__tylegislationsource				FROM STAGING__tylegislationsource;
SELECT COUNT(*)	STAGING__tylegislationtype					FROM STAGING__tylegislationtype;
SELECT COUNT(*)	STAGING__TYRATIONAL							FROM STAGING__TYRATIONAL;
SELECT COUNT(*)	STAGING__UNPLANNED_FORECAST					FROM STAGING__UNPLANNED_FORECAST;
SELECT COUNT(*)	STAGING__VIOLATIONS							FROM STAGING__VIOLATIONS;
SELECT COUNT(*)	STAGING__WORK_ORDERS						FROM STAGING__WORK_ORDERS;
SELECT COUNT(*)	STAGING__WORKORDERTYPE						FROM STAGING__WORKORDERTYPE;
SELECT COUNT(*) SOURCE__DATA_CONSOLIDATION FROM  SOURCE__DATA_CONSOLIDATION;

SELECT SUM(RECORD_COUNT) RECORD_COUNT FROM 
(
	SELECT COUNT(*)	RECORD_COUNT FROM SSIS_RegulatedEntityErrors UNION
	SELECT COUNT(*)	RECORD_COUNT FROM SSIS_SiteErrors UNION
	SELECT COUNT(*)	RECORD_COUNT FROM SSIS_WorkOrderErrors UNION
	SELECT COUNT(*)	RECORD_COUNT FROM CRM__BOOKABLERESOURCE UNION
	SELECT COUNT(*)	RECORD_COUNT FROM CRM__BUSINESSUNIT UNION
	SELECT COUNT(*)	RECORD_COUNT FROM CRM__PRICELEVEL UNION
	SELECT COUNT(*)	RECORD_COUNT FROM CRM__SYSTEMUSER UNION
	SELECT COUNT(*)	RECORD_COUNT FROM CRM__TEAM UNION
	SELECT COUNT(*)	RECORD_COUNT FROM STAGING__ACCOUNT UNION
	SELECT COUNT(*)	RECORD_COUNT FROM STAGING__accountclass UNION
	SELECT COUNT(*)	RECORD_COUNT FROM STAGING__BOOKABLE_RESOURCE UNION
	SELECT COUNT(*)	RECORD_COUNT FROM STAGING__BOOKABLE_RESOURCE_CATEGORIES UNION
	SELECT COUNT(*)	RECORD_COUNT FROM STAGING__BOOKABLE_RESOURCE_CATEGORY_ASSN UNION
	SELECT COUNT(*)	RECORD_COUNT FROM STAGING__COC UNION
	SELECT COUNT(*)	RECORD_COUNT FROM STAGING__CONTACT UNION
	SELECT COUNT(*)	RECORD_COUNT FROM STAGING__ENVIRONMENT_SETTINGS UNION
	SELECT COUNT(*)	RECORD_COUNT FROM STAGING__EQUIPMENT_TYPE UNION
	SELECT COUNT(*)	RECORD_COUNT FROM STAGING__OVERSIGHTTYPE UNION
	SELECT COUNT(*)	RECORD_COUNT FROM STAGING__TERRITORY UNION
	SELECT COUNT(*)	RECORD_COUNT FROM STAGING__tylegislation UNION
	SELECT COUNT(*)	RECORD_COUNT FROM STAGING__tylegislationsource UNION
	SELECT COUNT(*)	RECORD_COUNT FROM STAGING__tylegislationtype UNION
	SELECT COUNT(*)	RECORD_COUNT FROM STAGING__TYRATIONAL UNION
	SELECT COUNT(*)	RECORD_COUNT FROM STAGING__UNPLANNED_FORECAST UNION
	SELECT COUNT(*)	RECORD_COUNT FROM STAGING__VIOLATIONS UNION
	SELECT COUNT(*)	RECORD_COUNT FROM STAGING__WORK_ORDERS UNION
	SELECT COUNT(*)	RECORD_COUNT FROM STAGING__WORKORDERTYPE UNION
	SELECT COUNT(*) RECORD_COUNT FROM  SOURCE__DATA_CONSOLIDATION
) RECORD_COUNTS;