/****** Object:  Table [dbo].[01_IIS_DATA_CONSOLIDATION]    Script Date: 2021-03-25 9:30:08 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

DROP TABLE IF EXISTS [dbo].[01_IIS_DATA_CONSOLIDATION];
CREATE TABLE [dbo].[01_IIS_DATA_CONSOLIDATION] (
	[COMPLETED] [nvarchar](10) NULL,
	[ASSIGNED_TO] [nvarchar](100) NULL,
	[IIS_ID] [numeric](18, 0) NULL,
	[COMPANY_NAME_FORMATTED] [nvarchar](500) NULL,
	[PLANNED2021] [nvarchar](10) NULL,
	[COMPANY_NAME] [nvarchar](500) NULL,
	[COUNTRY_SUBDIVISION_CD] [nvarchar](10) NULL,
	[CITY_TOWN_NAME_NM] [nvarchar](250) NULL,
	[ADDRESS] [nvarchar](1000) NULL,
	[POSTAL_CODE_TXT] [nvarchar](10) NULL,
	[FILE_STATUS_CD] [nvarchar](50) NULL,
	[SOUNDEX_NAME] [nvarchar](50) NULL,
	[MATCHING_ID] [numeric](18, 0) NULL,
	[FUZZY_MATCH] [nvarchar](500) NULL,
	[REGULATED_ENTITY_ID] [nvarchar](50) NULL,
	[REGULATED_ENTITY_NAME] [nvarchar](500) NULL,
	[CONSOLIDATED_COMMON_ENGLISH_NAME] [nvarchar](500) NULL,
	[CONSOLIDATED_COMMON_FRENCH_NAME] [nvarchar](500) NULL,
	[NOTES] [nvarchar](500) NULL
) ON [PRIMARY]
GO

DROP TABLE IF EXISTS [dbo].[02_REGULATED_ENTITIES];
CREATE TABLE [dbo].[02_REGULATED_ENTITIES] (
	[REGULATED_ENTITY_ID] [uniqueidentifier],
	[REGULATED_ENTITY_ID_SOURCE] [nvarchar](50) NULL,
	[IIS_ID] [numeric](18, 0) NULL,
	[REGULATED_ENTITY_NAME] [nvarchar](500) NULL,
	[CONSOLIDATED_COMMON_ENGLISH_NAME] [nvarchar](500) NULL,
	[CONSOLIDATED_COMMON_FRENCH_NAME] [nvarchar](500) NULL,
	[COUNTRY_SUBDIVISION_CD] [nvarchar](10) NULL,
	[CITY_TOWN_NAME_NM] [nvarchar](250) NULL,
	[ADDRESS] [nvarchar](1000) NULL,
	[POSTAL_CODE_TXT] [nvarchar](10) NULL,
	[COMPLETED] [nvarchar](10) NULL,
	[NOTES] [nvarchar](500) NULL
) ON [PRIMARY]
GO

DROP TABLE IF EXISTS [dbo].[03_SITES];
CREATE TABLE [dbo].[03_SITES] (
    [SITE_ID] [uniqueidentifier],
	[IIS_ID] [numeric](18, 0) NULL,
	[REGULATED_ENTITY_ID] [uniqueidentifier],
	[REGULATED_ENTITY_ID_SOURCE] [nvarchar](50) NULL,
	[COMPANY_NAME_FORMATTED] [nvarchar](500) NULL,
	[COMPANY_NAME] [nvarchar](500) NULL,
	[COUNTRY_SUBDIVISION_CD] [nvarchar](10) NULL,
	[CITY_TOWN_NAME_NM] [nvarchar](250) NULL,
	[ADDRESS] [nvarchar](1000) NULL,
	[POSTAL_CODE_TXT] [nvarchar](10) NULL,
	[COMPLETED] [nvarchar](10) NULL,
	[PLANNED2021] [nvarchar](10) NULL,
) ON [PRIMARY]

GO



IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[04_ACCOUNT]') AND type in (N'U'))
DROP TABLE [dbo].[04_ACCOUNT]
GO

CREATE TABLE [dbo].[04_ACCOUNT] (
	[Id] [uniqueidentifier] NOT NULL,
	[SinkCreatedOn] [datetime] NULL,
	[SinkModifiedOn] [datetime] NULL,
	[statecode] [int] NULL,
	[statuscode] [int] NULL,
	[address1_addresstypecode] [int] NULL,
	[msdyn_travelchargetype] [int] NULL,
	[paymenttermscode] [int] NULL,
	[address1_shippingmethodcode] [int] NULL,
	[accountcategorycode] [int] NULL,
	[address1_freighttermscode] [int] NULL,
	[preferredappointmenttimecode] [int] NULL,
	[accountclassificationcode] [int] NULL,
	[customersizecode] [int] NULL,
	[ownershipcode] [int] NULL,
	[address2_freighttermscode] [int] NULL,
	[preferredcontactmethodcode] [int] NULL,
	[industrycode] [int] NULL,
	[businesstypecode] [int] NULL,
	[shippingmethodcode] [int] NULL,
	[accountratingcode] [int] NULL,
	[address2_addresstypecode] [int] NULL,
	[customertypecode] [int] NULL,
	[address2_shippingmethodcode] [int] NULL,
	[preferredappointmentdaycode] [int] NULL,
	[territorycode] [int] NULL,
	[donotpostalmail] [bit] NULL,
	[creditonhold] [bit] NULL,
	[donotbulkpostalmail] [bit] NULL,
	[donotbulkemail] [bit] NULL,
	[donotfax] [bit] NULL,
	[donotemail] [bit] NULL,
	[followemail] [bit] NULL,
	[participatesinworkflow] [bit] NULL,
	[marketingonly] [bit] NULL,
	[isprivate] [bit] NULL,
	[merged] [bit] NULL,
	[donotphone] [bit] NULL,
	[donotsendmm] [bit] NULL,
	[msdyn_taxexempt] [bit] NULL,
	[createdonbehalfby] [uniqueidentifier] NULL,
	[createdonbehalfby_entitytype] [nvarchar](128) NULL,
	[originatingleadid] [uniqueidentifier] NULL,
	[originatingleadid_entitytype] [nvarchar](128) NULL,
	[territoryid] [uniqueidentifier] NULL,
	[territoryid_entitytype] [nvarchar](128) NULL,
	[slaid] [uniqueidentifier] NULL,
	[slaid_entitytype] [nvarchar](128) NULL,
	[ovs_country] [uniqueidentifier] NULL,
	[ovs_country_entitytype] [nvarchar](128) NULL,
	[parentaccountid] [uniqueidentifier] NULL,
	[parentaccountid_entitytype] [nvarchar](128) NULL,
	[msdyn_serviceterritory] [uniqueidentifier] NULL,
	[msdyn_serviceterritory_entitytype] [nvarchar](128) NULL,
	[primarycontactid] [uniqueidentifier] NULL,
	[primarycontactid_entitytype] [nvarchar](128) NULL,
	[owningbusinessunit] [uniqueidentifier] NULL,
	[owningbusinessunit_entitytype] [nvarchar](128) NULL,
	[modifiedonbehalfby] [uniqueidentifier] NULL,
	[modifiedonbehalfby_entitytype] [nvarchar](128) NULL,
	[msdyn_workhourtemplate] [uniqueidentifier] NULL,
	[msdyn_workhourtemplate_entitytype] [nvarchar](128) NULL,
	[owninguser] [uniqueidentifier] NULL,
	[owninguser_entitytype] [nvarchar](128) NULL,
	[createdbyexternalparty] [uniqueidentifier] NULL,
	[createdbyexternalparty_entitytype] [nvarchar](128) NULL,
	[modifiedby] [uniqueidentifier] NULL,
	[modifiedby_entitytype] [nvarchar](128) NULL,
	[owningteam] [uniqueidentifier] NULL,
	[owningteam_entitytype] [nvarchar](128) NULL,
	[slainvokedid] [uniqueidentifier] NULL,
	[slainvokedid_entitytype] [nvarchar](128) NULL,
	[preferredequipmentid] [uniqueidentifier] NULL,
	[preferredequipmentid_entitytype] [nvarchar](128) NULL,
	[transactioncurrencyid] [uniqueidentifier] NULL,
	[transactioncurrencyid_entitytype] [nvarchar](128) NULL,
	[msdyn_billingaccount] [uniqueidentifier] NULL,
	[msdyn_billingaccount_entitytype] [nvarchar](128) NULL,
	[masterid] [uniqueidentifier] NULL,
	[masterid_entitytype] [nvarchar](128) NULL,
	[modifiedbyexternalparty] [uniqueidentifier] NULL,
	[modifiedbyexternalparty_entitytype] [nvarchar](128) NULL,
	[defaultpricelevelid] [uniqueidentifier] NULL,
	[defaultpricelevelid_entitytype] [nvarchar](128) NULL,
	[createdby] [uniqueidentifier] NULL,
	[createdby_entitytype] [nvarchar](128) NULL,
	[msdyn_preferredresource] [uniqueidentifier] NULL,
	[msdyn_preferredresource_entitytype] [nvarchar](128) NULL,
	[preferredserviceid] [uniqueidentifier] NULL,
	[preferredserviceid_entitytype] [nvarchar](128) NULL,
	[msdyn_salestaxcode] [uniqueidentifier] NULL,
	[msdyn_salestaxcode_entitytype] [nvarchar](128) NULL,
	[preferredsystemuserid] [uniqueidentifier] NULL,
	[preferredsystemuserid_entitytype] [nvarchar](128) NULL,
	[ovs_sitetype] [uniqueidentifier] NULL,
	[ovs_sitetype_entitytype] [nvarchar](128) NULL,
	[ownerid] [uniqueidentifier] NULL,
	[ownerid_entitytype] [nvarchar](128) NULL,
	[aging90] [decimal](38, 2) NULL,
	[openrevenue] [decimal](38, 2) NULL,
	[aging30] [decimal](38, 2) NULL,
	[msdyn_travelcharge_base] [decimal](38, 2) NULL,
	[aging60_base] [decimal](38, 4) NULL,
	[creditlimit] [decimal](38, 2) NULL,
	[openrevenue_base] [decimal](38, 2) NULL,
	[creditlimit_base] [decimal](38, 4) NULL,
	[aging60] [decimal](38, 2) NULL,
	[revenue] [decimal](38, 2) NULL,
	[msdyn_travelcharge] [decimal](38, 2) NULL,
	[revenue_base] [decimal](38, 4) NULL,
	[aging90_base] [decimal](38, 4) NULL,
	[marketcap_base] [decimal](38, 4) NULL,
	[marketcap] [decimal](38, 2) NULL,
	[aging30_base] [decimal](38, 4) NULL,
	[emailaddress3] [nvarchar](100) NULL,
	[emailaddress2] [nvarchar](100) NULL,
	[emailaddress1] [nvarchar](100) NULL,
	[masteraccountidyominame] [nvarchar](100) NULL,
	[address1_city] [nvarchar](80) NULL,
	[msdyn_serviceterritoryname] [nvarchar](200) NULL,
	[modifiedon] [datetime] NULL,
	[websiteurl] [nvarchar](200) NULL,
	[address1_longitude] [decimal](38, 5) NULL,
	[entityimage_timestamp] [bigint] NULL,
	[sharesoutstanding] [int] NULL,
	[primarycontactidname] [nvarchar](100) NULL,
	[transactioncurrencyidname] [nvarchar](100) NULL,
	[msdyn_salestaxcodename] [nvarchar](100) NULL,
	[preferredsystemuseridyominame] [nvarchar](100) NULL,
	[telephone1] [nvarchar](50) NULL,
	[telephone2] [nvarchar](50) NULL,
	[opendeals_date] [datetime] NULL,
	[modifiedbyexternalpartyyominame] [nvarchar](100) NULL,
	[masteraccountidname] [nvarchar](100) NULL,
	[preferredsystemuseridname] [nvarchar](100) NULL,
	[address2_stateorprovince] [nvarchar](50) NULL,
	[address2_line2] [nvarchar](250) NULL,
	[msdyn_preferredresourcename] [nvarchar](100) NULL,
	[address1_line3] [nvarchar](250) NULL,
	[name] [nvarchar](160) NULL,
	[onholdtime] [int] NULL,
	[ovs_accountnameenglish] [nvarchar](100) NULL,
	[parentaccountidname] [nvarchar](100) NULL,
	[originatingleadidname] [nvarchar](100) NULL,
	[address1_utcoffset] [int] NULL,
	[numberofemployees] [int] NULL,
	[modifiedbyexternalpartyname] [nvarchar](100) NULL,
	[address1_telephone1] [nvarchar](50) NULL,
	[ovs_primarycontactemail] [nvarchar](100) NULL,
	[exchangerate] [decimal](38, 10) NULL,
	[address2_county] [nvarchar](50) NULL,
	[telephone3] [nvarchar](50) NULL,
	[fax] [nvarchar](50) NULL,
	[ovs_sitetypename] [nvarchar](100) NULL,
	[msdyn_taxexemptnumber] [nvarchar](20) NULL,
	[address2_latitude] [decimal](38, 5) NULL,
	[createdon] [datetime] NULL,
	[timespentbymeonemailandmeetings] [nvarchar](1250) NULL,
	[address1_composite] [nvarchar](max) NULL,
	[opendeals_state] [int] NULL,
	[address2_postalcode] [nvarchar](20) NULL,
	[lastusedincampaign] [datetime] NULL,
	[ovs_accountnamefrench] [nvarchar](100) NULL,
	[processid] [uniqueidentifier] NULL,
	[owneridyominame] [nvarchar](100) NULL,
	[entityimage_url] [nvarchar](200) NULL,
	[teamsfollowed] [int] NULL,
	[address2_line3] [nvarchar](250) NULL,
	[description] [nvarchar](max) NULL,
	[address2_city] [nvarchar](80) NULL,
	[timezoneruleversionnumber] [int] NULL,
	[address1_county] [nvarchar](50) NULL,
	[createdbyname] [nvarchar](100) NULL,
	[msdyn_workhourtemplatename] [nvarchar](100) NULL,
	[address1_line1] [nvarchar](250) NULL,
	[address2_postofficebox] [nvarchar](20) NULL,
	[address2_telephone1] [nvarchar](50) NULL,
	[address2_telephone2] [nvarchar](50) NULL,
	[address2_telephone3] [nvarchar](50) NULL,
	[originatingleadidyominame] [nvarchar](100) NULL,
	[address1_addressid] [uniqueidentifier] NULL,
	[traversedpath] [nvarchar](1250) NULL,
	[territoryidname] [nvarchar](100) NULL,
	[yominame] [nvarchar](160) NULL,
	[createdonbehalfbyname] [nvarchar](100) NULL,
	[address2_name] [nvarchar](200) NULL,
	[openrevenue_state] [int] NULL,
	[address1_country] [nvarchar](80) NULL,
	[primarysatoriid] [nvarchar](200) NULL,
	[owneridtype] [nvarchar](4000) NULL,
	[entityimageid] [uniqueidentifier] NULL,
	[primarytwitterid] [nvarchar](128) NULL,
	[owneridname] [nvarchar](100) NULL,
	[modifiedonbehalfbyname] [nvarchar](100) NULL,
	[overriddencreatedon] [datetime] NULL,
	[address2_composite] [nvarchar](max) NULL,
	[ovs_naicscode] [nvarchar](6) NULL,
	[address1_stateorprovince] [nvarchar](50) NULL,
	[preferredserviceidname] [nvarchar](100) NULL,
	[createdbyexternalpartyyominame] [nvarchar](100) NULL,
	[ovs_countryname] [nvarchar](100) NULL,
	[msdyn_billingaccountyominame] [nvarchar](160) NULL,
	[address1_telephone2] [nvarchar](50) NULL,
	[address1_telephone3] [nvarchar](50) NULL,
	[address1_postofficebox] [nvarchar](20) NULL,
	[createdonbehalfbyyominame] [nvarchar](100) NULL,
	[slainvokedidname] [nvarchar](100) NULL,
	[address2_country] [nvarchar](80) NULL,
	[sic] [nvarchar](20) NULL,
	[address2_utcoffset] [int] NULL,
	[accountnumber] [nvarchar](20) NULL,
	[address2_fax] [nvarchar](50) NULL,
	[ovs_primarycontactphone] [nvarchar](100) NULL,
	[address2_longitude] [decimal](38, 5) NULL,
	[ftpsiteurl] [nvarchar](200) NULL,
	[preferredequipmentidname] [nvarchar](100) NULL,
	[address1_primarycontactname] [nvarchar](100) NULL,
	[modifiedbyyominame] [nvarchar](100) NULL,
	[lastonholdtime] [datetime] NULL,
	[address1_line2] [nvarchar](250) NULL,
	[openrevenue_date] [datetime] NULL,
	[address2_upszone] [nvarchar](4) NULL,
	[address1_postalcode] [nvarchar](20) NULL,
	[tickersymbol] [nvarchar](10) NULL,
	[stageid] [uniqueidentifier] NULL,
	[utcconversiontimezonecode] [int] NULL,
	[createdbyexternalpartyname] [nvarchar](100) NULL,
	[ovs_iisid] [nvarchar](25) NULL,
	[defaultpricelevelidname] [nvarchar](100) NULL,
	[stockexchange] [nvarchar](20) NULL,
	[address2_addressid] [uniqueidentifier] NULL,
	[msdyn_billingaccountname] [nvarchar](160) NULL,
	[importsequencenumber] [int] NULL,
	[msdyn_workorderinstructions] [nvarchar](max) NULL,
	[ovs_legalname] [nvarchar](250) NULL,
	[versionnumber] [bigint] NULL,
	[accountid] [uniqueidentifier] NULL,
	[address1_name] [nvarchar](200) NULL,
	[address1_fax] [nvarchar](50) NULL,
	[address1_latitude] [decimal](38, 5) NULL,
	[primarycontactidyominame] [nvarchar](100) NULL,
	[modifiedbyname] [nvarchar](100) NULL,
	[createdbyyominame] [nvarchar](100) NULL,
	[address2_line1] [nvarchar](250) NULL,
	[address1_upszone] [nvarchar](4) NULL,
	[modifiedonbehalfbyyominame] [nvarchar](100) NULL,
	[slaname] [nvarchar](100) NULL,
	[parentaccountidyominame] [nvarchar](100) NULL,
	[address2_primarycontactname] [nvarchar](100) NULL,
	[opendeals] [int] NULL
) ON [PRIMARY] --TEXTIMAGE_ON [PRIMARY]
GO





DROP TABLE IF EXISTS [dbo].[05_TERRITORY_TRANSLATION];
CREATE TABLE [dbo].[05_TERRITORY_TRANSLATION] (
    [COUNTRY_SUBDIVISION_CD] nvarchar(10),
	[msdyn_serviceterritory] uniqueidentifier
) ON [PRIMARY]
GO


DROP TABLE IF EXISTS [dbo].[06_WORK_ORDERS];
CREATE TABLE [dbo].[06_WORK_ORDERS] (

createdby	UNIQUEIDENTIFIER							  null,
createdbyname	NVARCHAR (200)							  null,
createdbyyominame	NVARCHAR (200)						  null,
createdon	DATETIME									  null,
createdonbehalfby	UNIQUEIDENTIFIER					  null,
createdonbehalfbyname	NVARCHAR (200)					  null,
createdonbehalfbyyominame	NVARCHAR (200)				  null,
exchangerate	NUMERIC (38, 10)						  null,
importsequencenumber	INT								  null,
modifiedby	UNIQUEIDENTIFIER							  null,
modifiedbyname	NVARCHAR (200)							  null,
modifiedbyyominame	NVARCHAR (200)						  null,
modifiedon	DATETIME									  null,
modifiedonbehalfby	UNIQUEIDENTIFIER					  null,
modifiedonbehalfbyname	NVARCHAR (200)					  null,
modifiedonbehalfbyyominame	NVARCHAR (200)				  null,
msdyn_address1	NVARCHAR (250)							  null,
msdyn_address2	NVARCHAR (250)							  null,
msdyn_address3	NVARCHAR (250)							  null,
msdyn_addressname	NVARCHAR (250)						  null,
msdyn_agreement	UNIQUEIDENTIFIER						  null,
msdyn_agreementname	NVARCHAR (100)						  null,
msdyn_autonumbering	NVARCHAR (100)						  null,
msdyn_billingaccount	UNIQUEIDENTIFIER				  null,
msdyn_billingaccountname	NVARCHAR (160)				  null,
msdyn_billingaccountyominame	NVARCHAR (160)			  null,
msdyn_bookingsummary	ntext							  null,
msdyn_childindex	INT									  null,
msdyn_city	NVARCHAR (80)								  null,
msdyn_closedby	UNIQUEIDENTIFIER						  null,
msdyn_closedbyname	NVARCHAR (200)						  null,
msdyn_closedbyyominame	NVARCHAR (200)					  null,
msdyn_completedon	DATETIME							  null,
msdyn_country	NVARCHAR (80)							  null,
msdyn_customerasset	UNIQUEIDENTIFIER					  null,
msdyn_customerassetname	NVARCHAR (100)					  null,
msdyn_datewindowend	DATETIME							  null,
msdyn_datewindowstart	DATETIME						  null,
msdyn_estimatesubtotalamount	NUMERIC (38, 2)			  null,
msdyn_estimatesubtotalamount_base	NUMERIC (38, 2)		  null,
msdyn_firstarrivedon	DATETIME						  null,
msdyn_followupnote	ntext								  null,
msdyn_followuprequired	bit								  null,
msdyn_followuprequiredname	NVARCHAR (255)				  null,
msdyn_functionallocation	UNIQUEIDENTIFIER			  null,
msdyn_functionallocationname	NVARCHAR (60)			  null,
msdyn_instructions	ntext								  null,
msdyn_internalflags	ntext								  null,
msdyn_iotalert	UNIQUEIDENTIFIER						  null,
msdyn_iotalertname	NVARCHAR (100)						  null,
msdyn_isfollowup	bit									  null,
msdyn_isfollowupname	NVARCHAR (255)					  null,
msdyn_ismobile	bit										  null,
msdyn_ismobilename	NVARCHAR (255)						  null,
msdyn_latitude	FLOAT									  null,
msdyn_longitude	FLOAT									  null,
msdyn_mapcontrol	NVARCHAR (100)						  null,
msdyn_name	NVARCHAR (100)								  null,
msdyn_opportunityid	UNIQUEIDENTIFIER					  null,
msdyn_opportunityidname	NVARCHAR (300)					  null,
msdyn_parentworkorder	UNIQUEIDENTIFIER				  null,
msdyn_parentworkordername	NVARCHAR (100)				  null,
msdyn_postalcode	NVARCHAR (20)						  null,
msdyn_preferredresource	UNIQUEIDENTIFIER				  null,
msdyn_preferredresourcename	NVARCHAR (100)				  null,
msdyn_pricelist	UNIQUEIDENTIFIER						  null,
msdyn_pricelistname	NVARCHAR (100)						  null,
msdyn_primaryincidentdescription	ntext				  null,
msdyn_primaryincidentestimatedduration	INT				  null,
msdyn_primaryincidenttype	UNIQUEIDENTIFIER			  null,
msdyn_primaryincidenttypename	NVARCHAR (100)			  null,
msdyn_priority	UNIQUEIDENTIFIER						  null,
msdyn_priorityname	NVARCHAR (100)						  null,
msdyn_reportedbycontact	UNIQUEIDENTIFIER				  null,
msdyn_reportedbycontactname	NVARCHAR (160)				  null,
msdyn_reportedbycontactyominame	NVARCHAR (450)			  null,
msdyn_serviceaccount	UNIQUEIDENTIFIER				  null,
msdyn_serviceaccountname	NVARCHAR (160)				  null,
msdyn_serviceaccountyominame	NVARCHAR (160)			  null,
msdyn_servicerequest	UNIQUEIDENTIFIER				  null,
msdyn_servicerequestname	NVARCHAR (200)				  null,
msdyn_serviceterritory	UNIQUEIDENTIFIER				  null,
msdyn_serviceterritoryname	NVARCHAR (200)				  null,
msdyn_stateorprovince	NVARCHAR (50)					  null,
msdyn_substatus	UNIQUEIDENTIFIER						  null,
msdyn_substatusname	NVARCHAR (100)						  null,
msdyn_subtotalamount	NUMERIC (38, 2)					  null,
msdyn_subtotalamount_base	NUMERIC (38, 2)				  null,
msdyn_supportcontact	UNIQUEIDENTIFIER				  null,
msdyn_supportcontactname	NVARCHAR (100)				  null,
msdyn_systemstatus	INT									  null,
msdyn_systemstatusname	NVARCHAR (255)					  null,
msdyn_taxable	bit										  null,
msdyn_taxablename	NVARCHAR (255)						  null,
msdyn_taxcode	UNIQUEIDENTIFIER						  null,
msdyn_taxcodename	NVARCHAR (100)						  null,
msdyn_timeclosed	DATETIME							  null,
msdyn_timefrompromised	DATETIME						  null,
msdyn_timegroup	UNIQUEIDENTIFIER						  null,
msdyn_timegroupdetailselected	UNIQUEIDENTIFIER		  null,
msdyn_timegroupdetailselectedname	NVARCHAR (100)		  null,
msdyn_timegroupname	NVARCHAR (100)						  null,
msdyn_timetopromised	DATETIME						  null,
msdyn_timewindowend	DATETIME							  null,
msdyn_timewindowstart	DATETIME						  null,
msdyn_totalamount	NUMERIC (38, 2)						  null,
msdyn_totalamount_base	NUMERIC (38, 2)					  null,
msdyn_totalestimatedduration	INT						  null,
msdyn_totalsalestax	NUMERIC (38, 2)						  null,
msdyn_totalsalestax_base	NUMERIC (38, 2)				  null,
msdyn_workhourtemplate	UNIQUEIDENTIFIER				  null,
msdyn_workhourtemplatename	NVARCHAR (100)				  null,
msdyn_worklocation	INT									  null,
msdyn_worklocationname	NVARCHAR (255)					  null,
msdyn_workorderarrivaltimekpiid	UNIQUEIDENTIFIER		  null,
msdyn_workorderarrivaltimekpiidname	NVARCHAR (100)		  null,
msdyn_workorderid	UNIQUEIDENTIFIER					  null,
msdyn_workorderresolutionkpiid	UNIQUEIDENTIFIER		  null,
msdyn_workorderresolutionkpiidname	NVARCHAR (100)		  null,
msdyn_workordersummary	ntext							  null,
msdyn_workordertype	UNIQUEIDENTIFIER					  null,
msdyn_workordertypename	NVARCHAR (100)					  null,
overriddencreatedon	DATETIME							  null,
ovs_asset	UNIQUEIDENTIFIER							  null,
ovs_assetcategory	UNIQUEIDENTIFIER					  null,
ovs_assetcategoryname	NVARCHAR (100)					  null,
ovs_assetname	NVARCHAR (100)							  null,
ovs_currentfiscalquarter	UNIQUEIDENTIFIER			  null,
ovs_currentfiscalquartername	NVARCHAR (100)			  null,
ovs_fiscalquarter	UNIQUEIDENTIFIER					  null,
ovs_fiscalquartername	NVARCHAR (100)					  null,
ovs_fiscalyear	UNIQUEIDENTIFIER						  null,
ovs_fiscalyearname	NVARCHAR (100)						  null,
ovs_iisid	NVARCHAR (100)								  null,
ovs_mocid	NVARCHAR (100)								  null,
ovs_operationid	UNIQUEIDENTIFIER						  null,
ovs_operationidname	NVARCHAR (200)						  null,
ovs_operationtypeid	UNIQUEIDENTIFIER					  null,
ovs_operationtypeidname	NVARCHAR (100)					  null,
ovs_oversighttype	UNIQUEIDENTIFIER					  null,
ovs_oversighttypename	NVARCHAR (100)					  null,
ovs_ovscountry	UNIQUEIDENTIFIER						  null,
ovs_ovscountryname	NVARCHAR (100)						  null,
ovs_primaryinspector	UNIQUEIDENTIFIER				  null,
ovs_primaryinspectorname	NVARCHAR (100)				  null,
ovs_rational	UNIQUEIDENTIFIER						  null,
ovs_rationalname	NVARCHAR (100)						  null,
ovs_regulatedentity	UNIQUEIDENTIFIER					  null,
ovs_regulatedentityname	NVARCHAR (160)					  null,
ovs_regulatedentityyominame	NVARCHAR (160)				  null,
ovs_revisedquarterid	UNIQUEIDENTIFIER				  null,
ovs_revisedquarteridname	NVARCHAR (100)				  null,
ovs_rolluptestdeletemeafter	DATETIME					  null,
ovs_rolluptestdeletemeafter_date	DATETIME			  null,
ovs_rolluptestdeletemeafter_state	INT					  null,
ovs_secondaryinspector	UNIQUEIDENTIFIER				  null,
ovs_secondaryinspectorname	NVARCHAR (100)				  null,
ovs_siteofviolation	UNIQUEIDENTIFIER					  null,
ovs_siteofviolationname	NVARCHAR (160)					  null,
ovs_siteofviolationyominame	NVARCHAR (160)				  null,
ovs_tyrational	UNIQUEIDENTIFIER						  null,
ovs_tyrationalname	NVARCHAR (100)						  null,
ownerid	UNIQUEIDENTIFIER								  null,
owneridname	NVARCHAR (200)								  null,
owneridtype	NVARCHAR (64)								  null,
owneridyominame	NVARCHAR (200)							  null,
owningbusinessunit	UNIQUEIDENTIFIER					  null,
owningteam	UNIQUEIDENTIFIER							  null,
owninguser	UNIQUEIDENTIFIER							  null,
processid	UNIQUEIDENTIFIER							  null,
qm_blobpath	NVARCHAR (200)								  null,
qm_remote	bit											  null,
qm_remotename	NVARCHAR (255)							  null,
qm_reportcontactid	UNIQUEIDENTIFIER					  null,
qm_reportcontactidname	NVARCHAR (160)					  null,
qm_reportcontactidyominame	NVARCHAR (450)				  null,
stageid	UNIQUEIDENTIFIER								  null,
statecode	INT											  null,
statecodename	NVARCHAR (255)							  null,
statuscode	INT											  null,
statuscodename	NVARCHAR (255)							  null,
timezoneruleversionnumber	INT							  null,
transactioncurrencyid	UNIQUEIDENTIFIER				  null,
transactioncurrencyidname	NVARCHAR (100)				  null,
traversedpath	NVARCHAR (1250)							  null,
utcconversiontimezonecode	INT							  null,
versionnumber	bigint									  null

) ON [PRIMARY]
GO

DROP TABLE IF EXISTS [dbo].[07_VIOLATIONS];
CREATE TABLE [dbo].[07_VIOLATIONS] (
    [createdby] uniqueidentifier,
    [createdbyname] nvarchar(200),
    [createdbyyominame] nvarchar(200),
    [createdon] datetime,
    [createdonbehalfby] uniqueidentifier,
    [createdonbehalfbyname] nvarchar(200),
    [createdonbehalfbyyominame] nvarchar(200),
    [importsequencenumber] int,
    [modifiedby] uniqueidentifier,
    [modifiedbyname] nvarchar(200),
    [modifiedbyyominame] nvarchar(200),
    [modifiedon] datetime,
    [modifiedonbehalfby] uniqueidentifier,
    [modifiedonbehalfbyname] nvarchar(200),
    [modifiedonbehalfbyyominame] nvarchar(200),
    [overriddencreatedon] datetime,
    [ownerid] uniqueidentifier,
    [owneridname] nvarchar(200),
    [owneridtype] nvarchar(64),
    [owneridyominame] nvarchar(200),
    [owningbusinessunit] uniqueidentifier,
    [owningteam] uniqueidentifier,
    [owninguser] uniqueidentifier,
    [qm_approximatetotal] int,
    [qm_blobpath] nvarchar(200),
    [qm_cysafetyassessmentid] uniqueidentifier,
    [qm_cysafetyassessmentidname] nvarchar(100),
    [qm_externalcomments] nvarchar(max),
    [qm_internalcomments] nvarchar(max),
    [qm_isviolation] bit,
    [qm_isviolationname] nvarchar(255),
    [qm_name] nvarchar(300),
    [qm_questionid] uniqueidentifier,
    [qm_questionidname] nvarchar(300),
    [qm_rclegislationid] uniqueidentifier,
    [qm_rclegislationidname] nvarchar(100),
    [qm_referenceid] nvarchar(255),
    [qm_responseid] nvarchar(4000),
    [qm_samplesize] int,
    [qm_syresultid] uniqueidentifier,
    [qm_violationcount] int,
    [qm_workorderid] uniqueidentifier,
    [qm_workorderidname] nvarchar(100),
    [statecode] int,
    [statecodename] nvarchar(255),
    [statuscode] int,
    [statuscodename] nvarchar(255),
    [timezoneruleversionnumber] int,
    [utcconversiontimezonecode] int,
    [versionnumber] bigint,
    [msdyn_billingaccount] uniqueidentifier,
    [msdyn_billingaccountname] nvarchar(160),
    [msdyn_billingaccountyominame] nvarchar(160),
    [msdyn_preferredresource] uniqueidentifier,
    [msdyn_preferredresourcename] nvarchar(100),
    [msdyn_serviceterritory] uniqueidentifier,
    [ovs_iisid] nvarchar(100),
    [exchangerate] numeric(38,10),
    [msdyn_address1] nvarchar(250),
    [msdyn_address2] nvarchar(250),
    [msdyn_address3] nvarchar(250),
    [msdyn_addressname] nvarchar(250),
    [msdyn_agreement] uniqueidentifier,
    [msdyn_agreementname] nvarchar(100),
    [msdyn_autonumbering] nvarchar(100),
    [msdyn_bookingsummary] nvarchar(max),
    [msdyn_childindex] int,
    [msdyn_city] nvarchar(80),
    [msdyn_closedby] uniqueidentifier,
    [msdyn_closedbyname] nvarchar(200),
    [msdyn_closedbyyominame] nvarchar(200),
    [msdyn_completedon] datetime,
    [msdyn_country] nvarchar(80),
    [msdyn_customerasset] uniqueidentifier,
    [msdyn_customerassetname] nvarchar(100),
    [msdyn_datewindowend] datetime,
    [msdyn_datewindowstart] datetime,
    [msdyn_estimatesubtotalamount] numeric(38,2),
    [msdyn_estimatesubtotalamount_base] numeric(38,2),
    [msdyn_firstarrivedon] datetime,
    [msdyn_followupnote] nvarchar(max),
    [msdyn_followuprequired] bit,
    [msdyn_followuprequiredname] nvarchar(255),
    [msdyn_functionallocation] uniqueidentifier,
    [msdyn_functionallocationname] nvarchar(60),
    [msdyn_instructions] nvarchar(max),
    [msdyn_internalflags] nvarchar(max),
    [msdyn_iotalert] uniqueidentifier,
    [msdyn_iotalertname] nvarchar(100),
    [msdyn_isfollowup] bit,
    [msdyn_isfollowupname] nvarchar(255),
    [msdyn_ismobile] bit,
    [msdyn_ismobilename] nvarchar(255),
    [msdyn_latitude] float,
    [msdyn_longitude] float,
    [msdyn_mapcontrol] nvarchar(100),
    [msdyn_name] nvarchar(100),
    [msdyn_opportunityid] uniqueidentifier,
    [msdyn_opportunityidname] nvarchar(300),
    [msdyn_parentworkorder] uniqueidentifier,
    [msdyn_parentworkordername] nvarchar(100),
    [msdyn_postalcode] nvarchar(20),
    [msdyn_pricelist] uniqueidentifier,
    [msdyn_pricelistname] nvarchar(100),
    [msdyn_primaryincidentdescription] nvarchar(max),
    [msdyn_primaryincidentestimatedduration] int,
    [msdyn_primaryincidenttype] uniqueidentifier,
    [msdyn_primaryincidenttypename] nvarchar(100),
    [msdyn_priority] uniqueidentifier,
    [msdyn_priorityname] nvarchar(100),
    [msdyn_reportedbycontact] uniqueidentifier,
    [msdyn_reportedbycontactname] nvarchar(160),
    [msdyn_reportedbycontactyominame] nvarchar(450),
    [msdyn_serviceaccount] uniqueidentifier,
    [msdyn_serviceaccountname] nvarchar(160),
    [msdyn_serviceaccountyominame] nvarchar(160),
    [msdyn_servicerequest] uniqueidentifier,
    [msdyn_servicerequestname] nvarchar(200),
    [msdyn_serviceterritoryname] nvarchar(200),
    [msdyn_stateorprovince] nvarchar(50),
    [msdyn_substatus] uniqueidentifier,
    [msdyn_substatusname] nvarchar(100),
    [msdyn_subtotalamount] numeric(38,2),
    [msdyn_subtotalamount_base] numeric(38,2),
    [msdyn_supportcontact] uniqueidentifier,
    [msdyn_supportcontactname] nvarchar(100),
    [msdyn_systemstatus] int,
    [msdyn_systemstatusname] nvarchar(255),
    [msdyn_taxable] bit,
    [msdyn_taxablename] nvarchar(255),
    [msdyn_taxcode] uniqueidentifier,
    [msdyn_taxcodename] nvarchar(100),
    [msdyn_timeclosed] datetime,
    [msdyn_timefrompromised] datetime,
    [msdyn_timegroup] uniqueidentifier,
    [msdyn_timegroupdetailselected] uniqueidentifier,
    [msdyn_timegroupdetailselectedname] nvarchar(100),
    [msdyn_timegroupname] nvarchar(100),
    [msdyn_timetopromised] datetime,
    [msdyn_timewindowend] datetime,
    [msdyn_timewindowstart] datetime,
    [msdyn_totalamount] numeric(38,2),
    [msdyn_totalamount_base] numeric(38,2),
    [msdyn_totalestimatedduration] int,
    [msdyn_totalsalestax] numeric(38,2),
    [msdyn_totalsalestax_base] numeric(38,2),
    [msdyn_workhourtemplate] uniqueidentifier,
    [msdyn_workhourtemplatename] nvarchar(100),
    [msdyn_worklocation] int,
    [msdyn_worklocationname] nvarchar(255),
    [msdyn_workorderarrivaltimekpiid] uniqueidentifier,
    [msdyn_workorderarrivaltimekpiidname] nvarchar(100),
    [msdyn_workorderid] uniqueidentifier,
    [msdyn_workorderresolutionkpiid] uniqueidentifier,
    [msdyn_workorderresolutionkpiidname] nvarchar(100),
    [msdyn_workordersummary] nvarchar(max),
    [msdyn_workordertype] uniqueidentifier,
    [msdyn_workordertypename] nvarchar(100),
    [ovs_asset] uniqueidentifier,
    [ovs_assetcategory] uniqueidentifier,
    [ovs_assetcategoryname] nvarchar(100),
    [ovs_assetname] nvarchar(100),
    [ovs_currentfiscalquarter] uniqueidentifier,
    [ovs_currentfiscalquartername] nvarchar(100),
    [ovs_fiscalquarter] uniqueidentifier,
    [ovs_fiscalquartername] nvarchar(100),
    [ovs_fiscalyear] uniqueidentifier,
    [ovs_fiscalyearname] nvarchar(100),
    [ovs_mocid] nvarchar(100),
    [ovs_operationid] uniqueidentifier,
    [ovs_operationidname] nvarchar(200),
    [ovs_operationtypeid] uniqueidentifier,
    [ovs_operationtypeidname] nvarchar(100),
    [ovs_oversighttype] uniqueidentifier,
    [ovs_oversighttypename] nvarchar(100),
    [ovs_ovscountry] uniqueidentifier,
    [ovs_ovscountryname] nvarchar(100),
    [ovs_primaryinspector] uniqueidentifier,
    [ovs_primaryinspectorname] nvarchar(100),
    [ovs_rational] uniqueidentifier,
    [ovs_rationalname] nvarchar(100),
    [ovs_regulatedentity] uniqueidentifier,
    [ovs_regulatedentityname] nvarchar(160),
    [ovs_regulatedentityyominame] nvarchar(160),
    [ovs_revisedquarterid] uniqueidentifier,
    [ovs_revisedquarteridname] nvarchar(100),
    [ovs_rolluptestdeletemeafter] datetime,
    [ovs_rolluptestdeletemeafter_date] datetime,
    [ovs_rolluptestdeletemeafter_state] int,
    [ovs_secondaryinspector] uniqueidentifier,
    [ovs_secondaryinspectorname] nvarchar(100),
    [ovs_siteofviolation] uniqueidentifier,
    [ovs_siteofviolationname] nvarchar(160),
    [ovs_siteofviolationyominame] nvarchar(160),
    [ovs_tyrational] uniqueidentifier,
    [ovs_tyrationalname] nvarchar(100),
    [processid] uniqueidentifier,
    [qm_remote] bit,
    [qm_remotename] nvarchar(255),
    [qm_reportcontactid] uniqueidentifier,
    [qm_reportcontactidname] nvarchar(160),
    [qm_reportcontactidyominame] nvarchar(450),
    [stageid] uniqueidentifier,
    [transactioncurrencyid] uniqueidentifier,
    [transactioncurrencyidname] nvarchar(100),
    [traversedpath] nvarchar(1250)
) ON [PRIMARY]
GO


/****** Object:  Table [dbo].[08_NOP_IMPORT]    Script Date: 2021-04-05 9:08:01 PM ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[08_NOP_IMPORT]') AND type in (N'U'))
DROP TABLE [dbo].[08_NOP_IMPORT]
GO

CREATE TABLE [dbo].[08_NOP_IMPORT](
	[IIS_ID] [numeric](18, 0) NULL,
	[MOC_ID] [numeric](18, 0) NULL,
	[PREFIX] [nvarchar](20) NULL,
	[COMPANY_NAME] [nvarchar](500) NULL,
	[ADDRESS] [nvarchar](500) NULL,
	[POSTALCODE] [nvarchar](20) NULL,
	[CITY] [nvarchar](100) NULL,
	[ACTIVITY_ID] [numeric](18, 0) NULL,
	[PROVINCE] [nvarchar](20) NULL,
	[ZONE] [nvarchar](100) NULL,
	[REGION_provincial] [nvarchar](20) NULL,
	[REGION_inspector] [nvarchar](20) NULL,
	[REGION_IIS] [nvarchar](20) NULL,
	[PLANNED_INSPECTOR] [nvarchar](100) NULL,
	[Quarter_1] [bit] NULL,
	[Quarter_2] [bit] NULL,
	[Quarter_3] [bit] NULL,
	[Quarter_4] [bit] NULL,
	[PLANNED_SITE] [bit] NULL,
	[DUE_PRIORITY] [nvarchar](20) NULL,
	[ACTIVITY_type_main_iis] [nvarchar](100) NULL,
	[ACTIVITY_type_sub_iis] [nvarchar](100) NULL,
	[inspector_name1] [nvarchar](100) NULL,
	[inspector_name2] [nvarchar](100) NULL,
	[INSPECTION_DATE_DTE] [datetime] NULL,
	[VERIFICATION_IND] [bit] NULL,
	[DATE_CREATED_DTE] [datetime] NULL,
	[FILE_REMARKS_TXT] [text] NULL,
	[FILE_STATUS_CD] [nvarchar](20) NULL,
	[DATE_CURRENT_DTE] [datetime] NULL,
	[DATE_DELETED_DTE] [datetime] NULL,
	[DATE_LAST_UPDATE_DTE] [datetime] NULL,
	[CONSIGNMENT_IND] [bit] NULL,
	[CEP_Complete] [nvarchar](20) NULL,
	[REPORT_CATEGORY] [nvarchar](100) NULL,
	[REPORT_REGION] [nvarchar](20) NULL,
	[REPORT_QUARTER] [nvarchar](10) NULL,
	[FINAL_TABLE] [nvarchar](20) NULL,
	[CEP_duplicate] [bit] NULL,
	[MORE_THAN_PLANNED] [bit] NULL,
	[HARDCODED] [bit] NULL,
	[REVIEWED_BY_HQ] [bit] NULL,
	[FLAGGED_FOR_REGIONAL_REVIEW] [bit] NULL,
	[ACTION_REQUIRED] [nvarchar](1000) NULL,
	[MOC_SUBTYPE_ERROR] [nvarchar](1000) NULL,
	[activity_type_enm_full] [nvarchar](100) NULL,
	[HQ_ONLY_FLAG] [bit] NULL,
	[hubs_flag] [bit] NULL,
	[TYPE] [nvarchar](10) NULL,
	[CEP_WARNING] [nvarchar](100) NULL,
	[Cep_sample_flag] [bit] NULL,
	[MOC_SV_FLAG] [bit] NULL,
	[COVID_FLAG] [bit] NULL,
	[ACTIVITY_HARDCODED] [bit] NULL,
	[REGION_HARDCODED] [bit] NULL,
	[PRINTED] [nvarchar](10) NULL,
	[REMOTE_INSPECTION] [nvarchar](10) NULL,
	[REPLICATION_OF_REPORT_CATEGORY2] [nvarchar](100) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


DROP TABLE IF EXISTS [09_WORKPLAN_IMPORT];
CREATE TABLE [dbo].[09_WORKPLAN_IMPORT](
import_number							 int,
fiscal_year								 nvarchar  (10),
[TYPE]									 [nvarchar](500),
Administrative_Region					 [nvarchar](500),
IIS_ID									 [nvarchar](500),
MOC_ID									 [nvarchar](500),
MOC_ID_PREFIX							 [nvarchar](500),
COMPANY_NAME							 [nvarchar](500),
ADDRESS_CIVIC							 [nvarchar](500),
POSTALCODE								 [nvarchar](500),
CITY_CIVIC								 [nvarchar](500),
[ZONE]									 [nvarchar](500),
PROV_CIVIC								 [nvarchar](500),
LAT_CIVIC								 [nvarchar](500),
LONG_CIVIC								 [nvarchar](500),
ADDRESS_PHYSICAL						 [nvarchar](500),
CITY_PHYSICAL							 [nvarchar](500),
POSTAL_PHYSICAL							 [nvarchar](500),
PROV_PHYSICAL							 [nvarchar](500),
LAT_PHYSICAL							 [nvarchar](500),
LONG_PHYSICAL							 [nvarchar](500),
ADDRESS_GD								 [nvarchar](500),
CITY_GD									 [nvarchar](500),
POSTAL_GD								 [nvarchar](500),
PROV_GD									 [nvarchar](500),
COUNTRY									 [nvarchar](500),
OUT_OF_COUNTRY_FLAG						 [nvarchar](500),
REGION									 [nvarchar](500),
RISK_CATEGORY							 [nvarchar](500),
[EXPIRY_DATE]							 [nvarchar](500),
LAST_ACTIVITY_DATE						 [nvarchar](500),
LAST_ACTIVITY_TYPE						 [nvarchar](500),
DUE_PRIORITY							 [nvarchar](500),
PROGRAM									 [nvarchar](500),
PLANNED_GC_2018_2019					 [nvarchar](500),
PLANNED_GC_2017_2018					 [nvarchar](500),
PLANNED_FOR_2016_2017					 [nvarchar](500),
PLANNED_LAST_YEAR						 [nvarchar](500),
PLANNED_MOC_2017_2018					 [nvarchar](500),
PLANNED_MOC_2018_2019					 [nvarchar](500),
TYPE_OF_FACILITY						 [nvarchar](500),
FILESTATUS								 [nvarchar](500),
ISSUE_DATE								 [nvarchar](500),
LAST_INSPECTION_DATE					 [nvarchar](500),
HQ_ONLY_FLAG							 [nvarchar](500),
CURRENT_INSPECTOR						 [nvarchar](500),
QUARTER_1								 [nvarchar](500),
QUARTER_2								 [nvarchar](500),
QUARTER_3								 [nvarchar](500),
QUARTER_4								 [nvarchar](500),
CURRENTLY_PLANNED						 [nvarchar](500),
ORIGINAL_INSPECTOR						 [nvarchar](500),
ORIGINALLY_PLANNED						 [nvarchar](500),
IIS_PROFILE_QUALITY_CHECK				 [nvarchar](500),
IIS_ACTIVITY_DATE_1						 [nvarchar](500),
IIS_TYPE_1								 [nvarchar](500),
IIS_CONSIGNMENT_1						 [nvarchar](500),
IIS_PRIMARY_INSPECTOR_1					 [nvarchar](500),
IIS_SECONDARY_INSPECTOR_1				 [nvarchar](500),
IIS_CREATION_DATE_1						 [nvarchar](500),
IIS_QUALITY_CHECK_1						 [nvarchar](500),
IIS_CEP_DATA_1							 [nvarchar](500),
IIS_VIOLATION_LIST_1					 [nvarchar](500),
IIS_VIOLATION_COUNT_1					 [nvarchar](500),
IIS_ACTIVITY_DATE_2						 [nvarchar](500),
IIS_TYPE_2								 [nvarchar](500),
IIS_CONSIGNMENT_2						 [nvarchar](500),
IIS_PRIMARY_INSPECTOR_2					 [nvarchar](500),
IIS_SECONDARY_INSPECTOR_2				 [nvarchar](500),
IIS_CREATION_DATE_2						 [nvarchar](500),
IIS_QUALITY_CHECK_2						 [nvarchar](500),
IIS_CEP_DATA_2							 [nvarchar](500),
IIS_VIOLATION_LIST_2             		 [nvarchar](500),
IIS_VIOLATION_COUNT_2            		 [nvarchar](500),
IIS_ACTIVITY_DATE_3              		 [nvarchar](500),
IIS_TYPE_3                       		 [nvarchar](500),
IIS_CONSIGNMENT_3                		 [nvarchar](500),
IIS_PRIMARY_INSPECTOR_3          		 [nvarchar](500),
IIS_SECONDARY_INSPECTOR_3        		 [nvarchar](500),
IIS_CREATION_DATE_3              		 [nvarchar](500),
IIS_QUALITY_CHECK_3              		 [nvarchar](500),
IIS_CEP_DATA_3                   		 [nvarchar](500),
IIS_VIOLATION_LIST_3             		 [nvarchar](500),
IIS_VIOLATION_COUNT_3            		 [nvarchar](500),
IIS_ACTIVITY_DATE_4              		 [nvarchar](500),
IIS_TYPE_4                       		 [nvarchar](500),
IIS_CONSIGNMENT_4                		 [nvarchar](500),
IIS_PRIMARY_INSPECTOR_4          		 [nvarchar](500),
IIS_SECONDARY_INSPECTOR_4        		 [nvarchar](500),
IIS_CREATION_DATE_4              		 [nvarchar](500),
IIS_QUALITY_CHECK_4              		 [nvarchar](500),
IIS_CEP_DATA_4                   		 [nvarchar](500),
IIS_VIOLATION_LIST_4             		 [nvarchar](500),
IIS_VIOLATION_COUNT_4            		 [nvarchar](500),
IIS_ACTIVITY_DATE_5              		 [nvarchar](500),
IIS_TYPE_5                       		 [nvarchar](500),
IIS_CONSIGNMENT_5                		 [nvarchar](500),
IIS_PRIMARY_INSPECTOR_5          		 [nvarchar](500),
IIS_SECONDARY_INSPECTOR_5        		 [nvarchar](500),
IIS_CREATION_DATE_5              		 [nvarchar](500),
IIS_QUALITY_CHECK_5              		 [nvarchar](500),
IIS_CEP_DATA_5                   		 [nvarchar](500),
IIS_VIOLATION_COUNT_5            		 [nvarchar](500),
IIS_VIOLATION_LIST_5             		 [nvarchar](500),
IIS_ACTIVITY_DATE_6              		 [nvarchar](500),
IIS_TYPE_6                       		 [nvarchar](500),
IIS_CONSIGNMENT_6                		 [nvarchar](500),
IIS_PRIMARY_INSPECTOR_6          		 [nvarchar](500),
IIS_SECONDARY_INSPECTOR_6        		 [nvarchar](500),
IIS_CREATION_DATE_6              		 [nvarchar](500),
IIS_QUALITY_CHECK_6              		 [nvarchar](500),
IIS_CEP_DATA_6                   		 [nvarchar](500),
IIS_VIOLATION_COUNT_6            		 [nvarchar](500),
IIS_VIOLATION_LIST_6             		 [nvarchar](500),
JUSTIFICATION_FOR_NOT_INSPECTING 		 [nvarchar](500),
EXPLANATION                      		 [nvarchar](500),
DATE_MADE_INACTIVE               		 [nvarchar](500),
SITE_STATUS                      		 [nvarchar](500),
SITE_CLOSED_INDICATOR            		 [nvarchar](500),
DELETED_INDICATOR                		 [nvarchar](500),
CLOSED                           		 [nvarchar](500),
YEARS_SINCE_LAST_INSPECTION      		 [nvarchar](500),
TRANSLOAD_FLAG                   		 [nvarchar](500),
CEP_SAMPLE_FLAG                  		 [nvarchar](500),
ALBERTA_HWY                      		 [nvarchar](500),
HUBS_FLAG                        		 [nvarchar](500),
ALBERTA_DROP                     		 [nvarchar](500),
US_DROP                          		 [nvarchar](500),
MOC_ONLY_INDICATOR  					 [nvarchar](500)
) ON [PRIMARY]
GO


DROP TABLE IF EXISTS [dbo].[10_IIS_EXPORT];
CREATE TABLE [dbo].[10_IIS_EXPORT] (
    [STAKEHOLDER_ID] NVARCHAR(255),
    [FILE_STATUS_CD] NVARCHAR(255),
    [INVESTIGATION_IND] NVARCHAR(255),
    [PROSECUTION_IND] NVARCHAR(255),
    [BUSINESS_CATEGORY_CD] NVARCHAR(500),
    [LEGAL_NAME_ENM] NVARCHAR(500),
    [OPERATING_NAME_ENM] NVARCHAR(500),
    [AKA_NAME_ENM] NVARCHAR(500),
    [STREET_NUMBER_NUM] NVARCHAR(255),
    [STREET_NAME_NM] NVARCHAR(255),
    [CITY_TOWN_NAME_NM] NVARCHAR(255),
    [COUNTRY_SUBDIVISION_CD] NVARCHAR(255),
    [POSTAL_CODE_TXT] NVARCHAR(255),
    [PHYS_STREET_NUMBER_NUM] NVARCHAR(255),
    [PHYS_STREET_NAME_NM] NVARCHAR(255),
    [PHYS_CITY_TOWN_NAME_NM] NVARCHAR(255),
    [PHYS_COUNTRY_CD] NVARCHAR(255),
    [PHYS_COUNTRY_ENM] NVARCHAR(255),
    [PHYS_COUNTRY_FNM] NVARCHAR(255),
    [PHYS_COUNTRY_SUBDIVISION_CD] NVARCHAR(255),
    [PHYS_COUNTRY_SUBDIVISION_ENM] NVARCHAR(255),
    [PHYS_COUNTRY_SUBDIVISION_FNM] NVARCHAR(255),
    [PHYS_POSTAL_CODE_TXT] NVARCHAR(255),
    [USER_CONTACT] NVARCHAR(255),
    [LAST_ACTIVITY_DATE] NVARCHAR(255),
    [TRANSPORT_MODE_ETXT] NVARCHAR(2000),
    [TRANSPORT_MODE_FTXT] NVARCHAR(2000),
    [TRANSPORT_MODE_CD] NVARCHAR(2000),
    [DG_CLASS] NVARCHAR(4000),
    [UN_NUMBER] NVARCHAR(4000),
    [UNIT_SUITE_NUM] NVARCHAR(255),
    [LATITUDE_DEGREE_NBR] NVARCHAR(255),
    [LATITUDE_MINUTE_NBR] NVARCHAR(255),
    [LONGITUDE_DEGREE_NBR] NVARCHAR(255),
    [LONGITUDE_MINUTE_NBR] NVARCHAR(255),
    [PHYS_LATITUDE_DEGREE_NBR] NVARCHAR(255),
    [PHYS_LATITUDE_MINUTE_NBR] NVARCHAR(255),
    [PHYS_LONGITUDE_DEGREE_NBR] NVARCHAR(255),
    [PHYS_LONGITUDE_MINUTE_NBR] NVARCHAR(255),
    [CONTACT_PHONE] NVARCHAR(255),
    [CONTACT_BUSINESS_PHONE] NVARCHAR(255),
    [CONTACT_EMAIL] NVARCHAR(255),
    [CONTACT_TFH] NVARCHAR(255),
    [CONTACT_TXT] NVARCHAR(255)
) ON [PRIMARY]
GO


DROP TABLE IF EXISTS [dbo].[11_CONTACT];
CREATE TABLE [11_CONTACT] (
    [accountid] UNIQUEIDENTIFIER,
    [accountidname] NVARCHAR(160),
    [accountidyominame] NVARCHAR(160),
    [accountrolecode] INT,
    [accountrolecodename] NVARCHAR(255),
    [address1_addressid] UNIQUEIDENTIFIER,
    [address1_addresstypecode] INT,
    [address1_addresstypecodename] NVARCHAR(255),
    [address1_city] NVARCHAR(80),
    [address1_composite] NTEXT,
    [address1_country] NVARCHAR(80),
    [address1_county] NVARCHAR(50),
    [address1_fax] NVARCHAR(50),
    [address1_freighttermscode] INT,
    [address1_freighttermscodename] NVARCHAR(255),
    [address1_latitude] FLOAT,
    [address1_line1] NVARCHAR(250),
    [address1_line2] NVARCHAR(250),
    [address1_line3] NVARCHAR(250),
    [address1_longitude] FLOAT,
    [address1_name] NVARCHAR(200),
    [address1_postalcode] NVARCHAR(20),
    [address1_postofficebox] NVARCHAR(20),
    [address1_primarycontactname] NVARCHAR(100),
    [address1_shippingmethodcode] INT,
    [address1_shippingmethodcodename] NVARCHAR(255),
    [address1_stateorprovince] NVARCHAR(50),
    [address1_telephone1] NVARCHAR(50),
    [address1_telephone2] NVARCHAR(50),
    [address1_telephone3] NVARCHAR(50),
    [address1_upszone] NVARCHAR(4),
    [address1_utcoffset] INT,
    [address2_addressid] UNIQUEIDENTIFIER,
    [address2_addresstypecode] INT,
    [address2_addresstypecodename] NVARCHAR(255),
    [address2_city] NVARCHAR(80),
    [address2_composite] NTEXT,
    [address2_country] NVARCHAR(80),
    [address2_county] NVARCHAR(50),
    [address2_fax] NVARCHAR(50),
    [address2_freighttermscode] INT,
    [address2_freighttermscodename] NVARCHAR(255),
    [address2_latitude] FLOAT,
    [address2_line1] NVARCHAR(250),
    [address2_line2] NVARCHAR(250),
    [address2_line3] NVARCHAR(250),
    [address2_longitude] FLOAT,
    [address2_name] NVARCHAR(100),
    [address2_postalcode] NVARCHAR(20),
    [address2_postofficebox] NVARCHAR(20),
    [address2_primarycontactname] NVARCHAR(100),
    [address2_shippingmethodcode] INT,
    [address2_shippingmethodcodename] NVARCHAR(255),
    [address2_stateorprovince] NVARCHAR(50),
    [address2_telephone1] NVARCHAR(50),
    [address2_telephone2] NVARCHAR(50),
    [address2_telephone3] NVARCHAR(50),
    [address2_upszone] NVARCHAR(4),
    [address2_utcoffset] INT,
    [address3_addressid] UNIQUEIDENTIFIER,
    [address3_addresstypecode] INT,
    [address3_addresstypecodename] NVARCHAR(255),
    [address3_city] NVARCHAR(80),
    [address3_composite] NTEXT,
    [address3_country] NVARCHAR(80),
    [address3_county] NVARCHAR(50),
    [address3_fax] NVARCHAR(50),
    [address3_freighttermscode] INT,
    [address3_freighttermscodename] NVARCHAR(255),
    [address3_latitude] FLOAT,
    [address3_line1] NVARCHAR(250),
    [address3_line2] NVARCHAR(250),
    [address3_line3] NVARCHAR(250),
    [address3_longitude] FLOAT,
    [address3_name] NVARCHAR(200),
    [address3_postalcode] NVARCHAR(20),
    [address3_postofficebox] NVARCHAR(20),
    [address3_primarycontactname] NVARCHAR(100),
    [address3_shippingmethodcode] INT,
    [address3_shippingmethodcodename] NVARCHAR(255),
    [address3_stateorprovince] NVARCHAR(50),
    [address3_telephone1] NVARCHAR(50),
    [address3_telephone2] NVARCHAR(50),
    [address3_telephone3] NVARCHAR(50),
    [address3_upszone] NVARCHAR(4),
    [address3_utcoffset] INT,
    [aging30] NUMERIC(38, 2),
    [aging30_base] NUMERIC(38, 4),
    [aging60] NUMERIC(38, 2),
    [aging60_base] NUMERIC(38, 4),
    [aging90] NUMERIC(38, 2),
    [aging90_base] NUMERIC(38, 4),
    [anniversary] DATE,
    [annualincome] NUMERIC(38, 2),
    [annualincome_base] NUMERIC(38, 4),
    [assistantname] NVARCHAR(100),
    [assistantphone] NVARCHAR(50),
    [birthdate] DATE,
    [business2] NVARCHAR(50),
    [businesscard] NTEXT,
    [businesscardattributes] NVARCHAR(4000),
    [callback] NVARCHAR(50),
    [childrensnames] NVARCHAR(255),
    [company] NVARCHAR(50),
    [contactid] UNIQUEIDENTIFIER,
    [createdby] UNIQUEIDENTIFIER,
    [createdbyexternalparty] UNIQUEIDENTIFIER,
    [createdbyexternalpartyname] NVARCHAR(300),
    [createdbyexternalpartyyominame] NVARCHAR(300),
    [createdbyname] NVARCHAR(200),
    [createdbyyominame] NVARCHAR(200),
    [createdon] DATETIME,
    [createdonbehalfby] UNIQUEIDENTIFIER,
    [createdonbehalfbyname] NVARCHAR(200),
    [createdonbehalfbyyominame] NVARCHAR(200),
    [creditlimit] NUMERIC(38, 2),
    [creditlimit_base] NUMERIC(38, 4),
    [creditonhold] BIT,
    [creditonholdname] NVARCHAR(255),
    [customersizecode] INT,
    [customersizecodename] NVARCHAR(255),
    [customertypecode] INT,
    [customertypecodename] NVARCHAR(255),
    [defaultpricelevelid] UNIQUEIDENTIFIER,
    [defaultpricelevelidname] NVARCHAR(100),
    [department] NVARCHAR(100),
    [description] NTEXT,
    [donotbulkemail] BIT,
    [donotbulkemailname] NVARCHAR(255),
    [donotbulkpostalmail] BIT,
    [donotbulkpostalmailname] NVARCHAR(255),
    [donotemail] BIT,
    [donotemailname] NVARCHAR(255),
    [donotfax] BIT,
    [donotfaxname] NVARCHAR(255),
    [donotphone] BIT,
    [donotphonename] NVARCHAR(255),
    [donotpostalmail] BIT,
    [donotpostalmailname] NVARCHAR(255),
    [donotsendmarketingmaterialname] NVARCHAR(255),
    [donotsendmm] BIT,
    [educationcode] INT,
    [educationcodename] NVARCHAR(255),
    [emailaddress1] NVARCHAR(100),
    [emailaddress2] NVARCHAR(100),
    [emailaddress3] NVARCHAR(100),
    [employeeid] NVARCHAR(50),
    [entityimage] IMAGE,
    [entityimage_timestamp] BIGINT,
    [entityimage_url] NVARCHAR(200),
    [entityimageid] UNIQUEIDENTIFIER,
    [exchangerate] NUMERIC(38, 10),
    [externaluseridentifier] NVARCHAR(50),
    [familystatuscode] INT,
    [familystatuscodename] NVARCHAR(255),
    [fax] NVARCHAR(50),
    [firstname] NVARCHAR(50),
    [followemail] BIT,
    [followemailname] NVARCHAR(255),
    [ftpsiteurl] NVARCHAR(200),
    [fullname] NVARCHAR(160),
    [gendercode] INT,
    [gendercodename] NVARCHAR(255),
    [governmentid] NVARCHAR(50),
    [haschildrencode] INT,
    [haschildrencodename] NVARCHAR(255),
    [home2] NVARCHAR(50),
    [importsequencenumber] INT,
    [isbackofficecustomer] BIT,
    [isbackofficecustomername] NVARCHAR(255),
    [isprivatename] NVARCHAR(255),
    [jobtitle] NVARCHAR(100),
    [lastname] NVARCHAR(50),
    [lastonholdtime] DATETIME,
    [lastusedincampaign] DATETIME,
    [leadsourcecode] INT,
    [leadsourcecodename] NVARCHAR(255),
    [managername] NVARCHAR(100),
    [managerphone] NVARCHAR(50),
    [marketingonly] BIT,
    [marketingonlyname] NVARCHAR(255),
    [mastercontactidname] NVARCHAR(160),
    [mastercontactidyominame] NVARCHAR(160),
    [masterid] UNIQUEIDENTIFIER,
    [merged] BIT,
    [mergedname] NVARCHAR(255),
    [middlename] NVARCHAR(50),
    [mobilephone] NVARCHAR(50),
    [modifiedby] UNIQUEIDENTIFIER,
    [modifiedbyexternalparty] UNIQUEIDENTIFIER,
    [modifiedbyexternalpartyname] NVARCHAR(300),
    [modifiedbyexternalpartyyominame] NVARCHAR(300),
    [modifiedbyname] NVARCHAR(200),
    [modifiedbyyominame] NVARCHAR(200),
    [modifiedon] DATETIME,
    [modifiedonbehalfby] UNIQUEIDENTIFIER,
    [modifiedonbehalfbyname] NVARCHAR(200),
    [modifiedonbehalfbyyominame] NVARCHAR(200),
    [msdyn_gdproptout] BIT,
    [msdyn_gdproptoutname] NVARCHAR(255),
    [msdyn_orgchangestatus] INT,
    [msdyn_orgchangestatusname] NVARCHAR(255),
    [nickname] NVARCHAR(100),
    [numberofchildren] INT,
    [onholdtime] INT,
    [originatingleadid] UNIQUEIDENTIFIER,
    [originatingleadidname] NVARCHAR(160),
    [originatingleadidyominame] NVARCHAR(160),
    [overriddencreatedon] DATETIME,
    [ownerid] UNIQUEIDENTIFIER,
    [owneridname] NVARCHAR(200),
    [owneridtype] NVARCHAR(64),
    [owneridyominame] NVARCHAR(200),
    [owningbusinessunit] UNIQUEIDENTIFIER,
    [owningteam] UNIQUEIDENTIFIER,
    [owninguser] UNIQUEIDENTIFIER,
    [pager] NVARCHAR(50),
    [parentcontactid] UNIQUEIDENTIFIER,
    [parentcontactidname] NVARCHAR(160),
    [parentcontactidyominame] NVARCHAR(160),
    [parentcustomerid] UNIQUEIDENTIFIER,
    [parentcustomeridname] NVARCHAR(160),
    [parentcustomeridtype] NVARCHAR(64),
    [parentcustomeridyominame] NVARCHAR(450),
    [participatesinworkflow] BIT,
    [participatesinworkflowname] NVARCHAR(255),
    [paymenttermscode] INT,
    [paymenttermscodename] NVARCHAR(255),
    [preferredappointmentdaycode] INT,
    [preferredappointmentdaycodename] NVARCHAR(255),
    [preferredappointmenttimecode] INT,
    [preferredappointmenttimecodename] NVARCHAR(255),
    [preferredcontactmethodcode] INT,
    [preferredcontactmethodcodename] NVARCHAR(255),
    [preferredequipmentid] UNIQUEIDENTIFIER,
    [preferredequipmentidname] NVARCHAR(160),
    [preferredserviceid] UNIQUEIDENTIFIER,
    [preferredserviceidname] NVARCHAR(160),
    [preferredsystemuserid] UNIQUEIDENTIFIER,
    [preferredsystemuseridname] NVARCHAR(200),
    [preferredsystemuseridyominame] NVARCHAR(200),
    [processid] UNIQUEIDENTIFIER,
    [salutation] NVARCHAR(100),
    [shippingmethodcode] INT,
    [shippingmethodcodename] NVARCHAR(255),
    [slaid] UNIQUEIDENTIFIER,
    [slainvokedid] UNIQUEIDENTIFIER,
    [slainvokedidname] NVARCHAR(100),
    [slaname] NVARCHAR(100),
    [spousesname] NVARCHAR(100),
    [stageid] UNIQUEIDENTIFIER,
    [statecode] INT,
    [statecodename] NVARCHAR(255),
    [statuscode] INT,
    [statuscodename] NVARCHAR(255),
    [suffix] NVARCHAR(10),
    [teamsfollowed] INT,
    [telephone1] NVARCHAR(50),
    [telephone2] NVARCHAR(50),
    [telephone3] NVARCHAR(50),
    [territorycode] INT,
    [territorycodename] NVARCHAR(255),
    [timespentbymeonemailandmeetings] NVARCHAR(1250),
    [timezoneruleversionnumber] INT,
    [transactioncurrencyid] UNIQUEIDENTIFIER,
    [transactioncurrencyidname] NVARCHAR(100),
    [traversedpath] NVARCHAR(1250),
    [utcconversiontimezonecode] INT,
    [versionnumber] BIGINT,
    [websiteurl] NVARCHAR(200),
    [yomifirstname] NVARCHAR(150),
    [yomifullname] NVARCHAR(450),
    [yomilastname] NVARCHAR(150),
    [yomimiddlename] NVARCHAR(150)
) ON [PRIMARY]
GO

DROP TABLE IF EXISTS [dbo].[12_BOOKABLE_RESOURCE];
CREATE TABLE [12_BOOKABLE_RESOURCE] (
    [accountid] UNIQUEIDENTIFIER,
    [accountidname] NVARCHAR(160),
    [accountidyominame] NVARCHAR(160),
    [bookableresourceid] UNIQUEIDENTIFIER,
    [calendarid] UNIQUEIDENTIFIER,
    [calendaridname] NVARCHAR(160),
    [contactid] UNIQUEIDENTIFIER,
    [contactidname] NVARCHAR(160),
    [contactidyominame] NVARCHAR(160),
    [createdby] UNIQUEIDENTIFIER,
    [createdbyname] NVARCHAR(200),
    [createdbyyominame] NVARCHAR(200),
    [createdon] DATETIME,
    [createdonbehalfby] UNIQUEIDENTIFIER,
    [createdonbehalfbyname] NVARCHAR(200),
    [createdonbehalfbyyominame] NVARCHAR(200),
    [exchangerate] NUMERIC(38, 10),
    [importsequencenumber] INT,
    [modifiedby] UNIQUEIDENTIFIER,
    [modifiedbyname] NVARCHAR(200),
    [modifiedbyyominame] NVARCHAR(200),
    [modifiedon] DATETIME,
    [modifiedonbehalfby] UNIQUEIDENTIFIER,
    [modifiedonbehalfbyname] NVARCHAR(200),
    [modifiedonbehalfbyyominame] NVARCHAR(200),
    [msdyn_bookingstodrip] INT,
    [msdyn_crewstrategy] INT,
    [msdyn_crewstrategyname] NVARCHAR(255),
    [msdyn_derivecapacity] BIT,
    [msdyn_derivecapacityname] NVARCHAR(255),
    [msdyn_displayonscheduleassistant] BIT,
    [msdyn_displayonscheduleassistantname] NVARCHAR(255),
    [msdyn_displayonscheduleboard] BIT,
    [msdyn_displayonscheduleboardname] NVARCHAR(255),
    [msdyn_enableappointments] INT,
    [msdyn_enableappointmentsname] NVARCHAR(255),
    [msdyn_enabledforfieldservicemobile] BIT,
    [msdyn_enabledforfieldservicemobilename] NVARCHAR(255),
    [msdyn_enabledripscheduling] BIT,
    [msdyn_enabledripschedulingname] NVARCHAR(255),
    [msdyn_endlocation] INT,
    [msdyn_endlocationname] NVARCHAR(255),
    [msdyn_facilityequipmentid] UNIQUEIDENTIFIER,
    [msdyn_facilityequipmentidname] NVARCHAR(160),
    [msdyn_generictype] INT,
    [msdyn_generictypename] NVARCHAR(255),
    [msdyn_hourlyrate] NUMERIC(38, 2),
    [msdyn_hourlyrate_base] NUMERIC(38, 2),
    [msdyn_internalflags] NTEXT,
    [msdyn_latitude] FLOAT,
    [msdyn_locationtimestamp] DATETIME,
    [msdyn_longitude] FLOAT,
    [msdyn_organizationalunit] UNIQUEIDENTIFIER,
    [msdyn_organizationalunitname] NVARCHAR(100),
    [msdyn_pooltype] NVARCHAR(4000),
    [msdyn_pooltypename] NVARCHAR(255),
    [msdyn_primaryemail] NVARCHAR(100),
    [msdyn_startlocation] INT,
    [msdyn_startlocationname] NVARCHAR(255),
    [msdyn_targetutilization] INT,
    [msdyn_timeoffapprovalrequired] BIT,
    [msdyn_timeoffapprovalrequiredname] NVARCHAR(255),
    [msdyn_warehouse] UNIQUEIDENTIFIER,
    [msdyn_warehousename] NVARCHAR(100),
    [name] NVARCHAR(100),
    [overriddencreatedon] DATETIME,
    [ovs_badgenumber] NVARCHAR(100),
    [ovs_registeredinspectornumberrin] NVARCHAR(100),
    [ownerid] UNIQUEIDENTIFIER,
    [owneridname] NVARCHAR(200),
    [owneridtype] NVARCHAR(64),
    [owneridyominame] NVARCHAR(200),
    [owningbusinessunit] UNIQUEIDENTIFIER,
    [owningteam] UNIQUEIDENTIFIER,
    [owninguser] UNIQUEIDENTIFIER,
    [processid] UNIQUEIDENTIFIER,
    [resourcetype] INT,
    [resourcetypename] NVARCHAR(255),
    [stageid] UNIQUEIDENTIFIER,
    [statecode] INT,
    [statecodename] NVARCHAR(255),
    [statuscode] INT,
    [statuscodename] NVARCHAR(255),
    [timezone] INT,
    [timezoneruleversionnumber] INT,
    [transactioncurrencyid] UNIQUEIDENTIFIER,
    [transactioncurrencyidname] NVARCHAR(100),
    [traversedpath] NVARCHAR(1250),
    [userid] UNIQUEIDENTIFIER,
    [useridname] NVARCHAR(200),
    [useridyominame] NVARCHAR(200),
    [utcconversiontimezonecode] INT,
    [versionnumber] BIGINT
) ON [PRIMARY]
GO


DROP TABLE IF EXISTS [dbo].[13_FISCAL_YEAR];
CREATE TABLE [13_FISCAL_YEAR] (
    [createdby] UNIQUEIDENTIFIER,
    [createdbyname] NVARCHAR(200),
    [createdbyyominame] NVARCHAR(200),
    [createdon] DATETIME,
    [createdonbehalfby] UNIQUEIDENTIFIER,
    [createdonbehalfbyname] NVARCHAR(200),
    [createdonbehalfbyyominame] NVARCHAR(200),
    [importsequencenumber] INT,
    [modifiedby] UNIQUEIDENTIFIER,
    [modifiedbyname] NVARCHAR(200),
    [modifiedbyyominame] NVARCHAR(200),
    [modifiedon] DATETIME,
    [modifiedonbehalfby] UNIQUEIDENTIFIER,
    [modifiedonbehalfbyname] NVARCHAR(200),
    [modifiedonbehalfbyyominame] NVARCHAR(200),
    [overriddencreatedon] DATETIME,
    [ownerid] UNIQUEIDENTIFIER,
    [owneridname] NVARCHAR(200),
    [owneridtype] NVARCHAR(64),
    [owneridyominame] NVARCHAR(200),
    [owningbusinessunit] UNIQUEIDENTIFIER,
    [owningteam] UNIQUEIDENTIFIER,
    [owninguser] UNIQUEIDENTIFIER,
    [statecode] INT,
    [statecodename] NVARCHAR(255),
    [statuscode] INT,
    [statuscodename] NVARCHAR(255),
    [tc_fiscalend] DATETIME,
    [tc_fiscalstart] DATETIME,
    [tc_fiscalyearlonglbl] NVARCHAR(100),
    [tc_fiscalyearnum] NVARCHAR(100),
    [tc_iscurrentfiscalyear] BIT,
    [tc_iscurrentfiscalyearname] NVARCHAR(255),
    [tc_name] NVARCHAR(100),
    [tc_tcfiscalyearid] UNIQUEIDENTIFIER,
    [tc_todaysdate] DATETIME,
    [timezoneruleversionnumber] INT,
    [utcconversiontimezonecode] INT,
    [versionnumber] BIGINT
)  ON [PRIMARY]
GO


DROP TABLE IF EXISTS [dbo].[14_FISCAL_QUARTER];
CREATE TABLE [14_FISCAL_QUARTER] (
    [createdby] UNIQUEIDENTIFIER,
    [createdbyname] NVARCHAR(200),
    [createdbyyominame] NVARCHAR(200),
    [createdon] DATETIME,
    [createdonbehalfby] UNIQUEIDENTIFIER,
    [createdonbehalfbyname] NVARCHAR(200),
    [createdonbehalfbyyominame] NVARCHAR(200),
    [importsequencenumber] INT,
    [modifiedby] UNIQUEIDENTIFIER,
    [modifiedbyname] NVARCHAR(200),
    [modifiedbyyominame] NVARCHAR(200),
    [modifiedon] DATETIME,
    [modifiedonbehalfby] UNIQUEIDENTIFIER,
    [modifiedonbehalfbyname] NVARCHAR(200),
    [modifiedonbehalfbyyominame] NVARCHAR(200),
    [overriddencreatedon] DATETIME,
    [ownerid] UNIQUEIDENTIFIER,
    [owneridname] NVARCHAR(200),
    [owneridtype] NVARCHAR(64),
    [owneridyominame] NVARCHAR(200),
    [owningbusinessunit] UNIQUEIDENTIFIER,
    [owningteam] UNIQUEIDENTIFIER,
    [owninguser] UNIQUEIDENTIFIER,
    [statecode] INT,
    [statecodename] NVARCHAR(255),
    [statuscode] INT,
    [statuscodename] NVARCHAR(255),
    [tc_fiscalquarterlbl] NVARCHAR(100),
    [tc_fiscalquarterlonglbl] NVARCHAR(100),
    [tc_fiscalquarternum] INT,
    [tc_name] NVARCHAR(100),
    [tc_quarterend] DATETIME,
    [tc_quarterstart] DATETIME,
    [tc_tcfiscalquarterid] UNIQUEIDENTIFIER,
    [tc_tcfiscalyearid] UNIQUEIDENTIFIER,
    [tc_tcfiscalyearidname] NVARCHAR(100),
    [timezoneruleversionnumber] INT,
    [utcconversiontimezonecode] INT,
    [versionnumber] BIGINT
)  ON [PRIMARY]
GO


DROP TABLE IF EXISTS [dbo].[15_SYSTEM_USER];
CREATE TABLE [15_SYSTEM_USER] (
    [accessmode] INT,
    [accessmodename] NVARCHAR(255),
    [address1_addressid] UNIQUEIDENTIFIER,
    [address1_addresstypecode] INT,
    [address1_addresstypecodename] NVARCHAR(255),
    [address1_city] NVARCHAR(128),
    [address1_composite] NTEXT,
    [address1_country] NVARCHAR(128),
    [address1_county] NVARCHAR(128),
    [address1_fax] NVARCHAR(64),
    [address1_latitude] FLOAT,
    [address1_line1] NVARCHAR(1024),
    [address1_line2] NVARCHAR(1024),
    [address1_line3] NVARCHAR(1024),
    [address1_longitude] FLOAT,
    [address1_name] NVARCHAR(100),
    [address1_postalcode] NVARCHAR(40),
    [address1_postofficebox] NVARCHAR(40),
    [address1_shippingmethodcode] INT,
    [address1_shippingmethodcodename] NVARCHAR(255),
    [address1_stateorprovince] NVARCHAR(128),
    [address1_telephone1] NVARCHAR(64),
    [address1_telephone2] NVARCHAR(50),
    [address1_telephone3] NVARCHAR(50),
    [address1_upszone] NVARCHAR(4),
    [address1_utcoffset] INT,
    [address2_addressid] UNIQUEIDENTIFIER,
    [address2_addresstypecode] INT,
    [address2_addresstypecodename] NVARCHAR(255),
    [address2_city] NVARCHAR(128),
    [address2_composite] NTEXT,
    [address2_country] NVARCHAR(128),
    [address2_county] NVARCHAR(128),
    [address2_fax] NVARCHAR(50),
    [address2_latitude] FLOAT,
    [address2_line1] NVARCHAR(1024),
    [address2_line2] NVARCHAR(1024),
    [address2_line3] NVARCHAR(1024),
    [address2_longitude] FLOAT,
    [address2_name] NVARCHAR(100),
    [address2_postalcode] NVARCHAR(40),
    [address2_postofficebox] NVARCHAR(40),
    [address2_shippingmethodcode] INT,
    [address2_shippingmethodcodename] NVARCHAR(255),
    [address2_stateorprovince] NVARCHAR(128),
    [address2_telephone1] NVARCHAR(50),
    [address2_telephone2] NVARCHAR(50),
    [address2_telephone3] NVARCHAR(50),
    [address2_upszone] NVARCHAR(4),
    [address2_utcoffset] INT,
    [applicationid] UNIQUEIDENTIFIER,
    [applicationiduri] NVARCHAR(1024),
    [azureactivedirectoryobjectid] UNIQUEIDENTIFIER,
    [businessunitid] UNIQUEIDENTIFIER,
    [businessunitidname] NVARCHAR(160),
    [calendarid] UNIQUEIDENTIFIER,
    [caltype] INT,
    [caltypename] NVARCHAR(255),
    [createdby] UNIQUEIDENTIFIER,
    [createdbyname] NVARCHAR(200),
    [createdbyyominame] NVARCHAR(200),
    [createdon] DATETIME,
    [createdonbehalfby] UNIQUEIDENTIFIER,
    [createdonbehalfbyname] NVARCHAR(200),
    [createdonbehalfbyyominame] NVARCHAR(200),
    [defaultfilterspopulated] BIT,
    [defaultmailbox] UNIQUEIDENTIFIER,
    [defaultmailboxname] NVARCHAR(200),
    [defaultodbfoldername] NVARCHAR(200),
    [disabledreason] NVARCHAR(500),
    [displayinserviceviews] BIT,
    [displayinserviceviewsname] NVARCHAR(255),
    [domainname] NVARCHAR(1024),
    [emailrouteraccessapproval] INT,
    [emailrouteraccessapprovalname] NVARCHAR(255),
    [employeeid] NVARCHAR(100),
    [entityimage] IMAGE,
    [entityimage_timestamp] BIGINT,
    [entityimage_url] NVARCHAR(200),
    [entityimageid] UNIQUEIDENTIFIER,
    [exchangerate] NUMERIC(38, 10),
    [firstname] NVARCHAR(256),
    [fullname] NVARCHAR(200),
    [governmentid] NVARCHAR(100),
    [homephone] NVARCHAR(50),
    [identityid] INT,
    [importsequencenumber] INT,
    [incomingemaildeliverymethod] INT,
    [incomingemaildeliverymethodname] NVARCHAR(255),
    [internalemailaddress] NVARCHAR(100),
    [invitestatuscode] INT,
    [invitestatuscodename] NVARCHAR(255),
    [isdisabled] BIT,
    [isdisabledname] NVARCHAR(255),
    [isemailaddressapprovedbyo365admin] BIT,
    [isintegrationuser] BIT,
    [isintegrationusername] NVARCHAR(255),
    [islicensed] BIT,
    [islicensedname] NVARCHAR(255),
    [issyncwithdirectory] BIT,
    [jobtitle] NVARCHAR(100),
    [lastname] NVARCHAR(256),
    [middlename] NVARCHAR(50),
    [mobilealertemail] NVARCHAR(100),
    [mobileofflineprofileid] UNIQUEIDENTIFIER,
    [mobileofflineprofileidname] NVARCHAR(255),
    [mobilephone] NVARCHAR(64),
    [modifiedby] UNIQUEIDENTIFIER,
    [modifiedbyname] NVARCHAR(200),
    [modifiedbyyominame] NVARCHAR(200),
    [modifiedon] DATETIME,
    [modifiedonbehalfby] UNIQUEIDENTIFIER,
    [modifiedonbehalfbyname] NVARCHAR(200),
    [modifiedonbehalfbyyominame] NVARCHAR(200),
    [msdyn_gdproptout] BIT,
    [msdyn_gdproptoutname] NVARCHAR(255),
    [nickname] NVARCHAR(50),
    [organizationid] UNIQUEIDENTIFIER,
    [organizationidname] NVARCHAR(100),
    [outgoingemaildeliverymethod] INT,
    [outgoingemaildeliverymethodname] NVARCHAR(255),
    [overriddencreatedon] DATETIME,
    [parentsystemuserid] UNIQUEIDENTIFIER,
    [parentsystemuseridname] NVARCHAR(200),
    [parentsystemuseridyominame] NVARCHAR(200),
    [passporthi] INT,
    [passportlo] INT,
    [personalemailaddress] NVARCHAR(100),
    [photourl] NVARCHAR(200),
    [positionid] UNIQUEIDENTIFIER,
    [positionidname] NVARCHAR(100),
    [preferredaddresscode] INT,
    [preferredaddresscodename] NVARCHAR(255),
    [preferredemailcode] INT,
    [preferredemailcodename] NVARCHAR(255),
    [preferredphonecode] INT,
    [preferredphonecodename] NVARCHAR(255),
    [processid] UNIQUEIDENTIFIER,
    [queueid] UNIQUEIDENTIFIER,
    [queueidname] NVARCHAR(400),
    [salutation] NVARCHAR(20),
    [setupuser] BIT,
    [setupusername] NVARCHAR(255),
    [sharepointemailaddress] NVARCHAR(1024),
    [siteid] UNIQUEIDENTIFIER,
    [siteidname] NVARCHAR(160),
    [skills] NVARCHAR(100),
    [stageid] UNIQUEIDENTIFIER,
    [systemuserid] UNIQUEIDENTIFIER,
    [territoryid] UNIQUEIDENTIFIER,
    [territoryidname] NVARCHAR(200),
    [timezoneruleversionnumber] INT,
    [title] NVARCHAR(128),
    [transactioncurrencyid] UNIQUEIDENTIFIER,
    [transactioncurrencyidname] NVARCHAR(100),
    [traversedpath] NVARCHAR(1250),
    [userlicensetype] INT,
    [userpuid] NVARCHAR(100),
    [utcconversiontimezonecode] INT,
    [versionnumber] BIGINT,
    [windowsliveid] NVARCHAR(1024),
    [yammeremailaddress] NVARCHAR(200),
    [yammeruserid] NVARCHAR(128),
    [yomifirstname] NVARCHAR(64),
    [yomifullname] NVARCHAR(200),
    [yomilastname] NVARCHAR(64),
    [yomimiddlename] NVARCHAR(50)
) ON [PRIMARY]
GO

DROP TABLE [dbo].[16_IIS_INSPECTORS];
CREATE TABLE [dbo].[16_IIS_INSPECTORS](
	[USER_ID] [nvarchar](255) NULL,
	[First Name] [nvarchar](255) NULL,
	[Last Name] [nvarchar](255) NULL,
	[Fullname] [nvarchar](255) NULL,
	[Account_name] [nvarchar](255) NULL,
	[BADGE] [nvarchar](255) NULL,
	[RIN] [nvarchar](255) NULL,
	[RegionCrmId] [nvarchar](255) NULL,
	[Region] [nvarchar](255) NULL,
	[RegionEnm] [nvarchar](255) NULL,
	[RegionFnm] [nvarchar](255) NULL
) ON [PRIMARY]
GO

DROP TABLE [dbo].[17_BOOKABLE_RESOURCE_CATEGORIES];
CREATE TABLE [17_BOOKABLE_RESOURCE_CATEGORIES] (
    [bookableresourcecategoryid] UNIQUEIDENTIFIER,
    [createdby] UNIQUEIDENTIFIER,
    [createdbyname] NVARCHAR(200),
    [createdbyyominame] NVARCHAR(200),
    [createdon] DATETIME,
    [createdonbehalfby] UNIQUEIDENTIFIER,
    [createdonbehalfbyname] NVARCHAR(200),
    [createdonbehalfbyyominame] NVARCHAR(200),
    [description] NVARCHAR(100),
    [exchangerate] NUMERIC(38, 10),
    [importsequencenumber] INT,
    [modifiedby] UNIQUEIDENTIFIER,
    [modifiedbyname] NVARCHAR(200),
    [modifiedbyyominame] NVARCHAR(200),
    [modifiedon] DATETIME,
    [modifiedonbehalfby] UNIQUEIDENTIFIER,
    [modifiedonbehalfbyname] NVARCHAR(200),
    [modifiedonbehalfbyyominame] NVARCHAR(200),
    [name] NVARCHAR(100),
    [overriddencreatedon] DATETIME,
    [ownerid] UNIQUEIDENTIFIER,
    [owneridname] NVARCHAR(200),
    [owneridtype] NVARCHAR(64),
    [owneridyominame] NVARCHAR(200),
    [owningbusinessunit] UNIQUEIDENTIFIER,
    [owningteam] UNIQUEIDENTIFIER,
    [owninguser] UNIQUEIDENTIFIER,
    [statecode] INT,
    [statecodename] NVARCHAR(255),
    [statuscode] INT,
    [statuscodename] NVARCHAR(255),
    [timezoneruleversionnumber] INT,
    [transactioncurrencyid] UNIQUEIDENTIFIER,
    [transactioncurrencyidname] NVARCHAR(100),
    [utcconversiontimezonecode] INT,
    [versionnumber] BIGINT
) ON [PRIMARY]
GO

DROP TABLE [dbo].[18_BOOKABLE_RESOURCE_CATEGORY_ASSN];
CREATE TABLE [18_BOOKABLE_RESOURCE_CATEGORY_ASSN] (
    [bookableresourcecategoryassnid] UNIQUEIDENTIFIER,
    [createdby] UNIQUEIDENTIFIER,
    [createdbyname] NVARCHAR(200),
    [createdbyyominame] NVARCHAR(200),
    [createdon] DATETIME,
    [createdonbehalfby] UNIQUEIDENTIFIER,
    [createdonbehalfbyname] NVARCHAR(200),
    [createdonbehalfbyyominame] NVARCHAR(200),
    [exchangerate] NUMERIC(38, 10),
    [importsequencenumber] INT,
    [modifiedby] UNIQUEIDENTIFIER,
    [modifiedbyname] NVARCHAR(200),
    [modifiedbyyominame] NVARCHAR(200),
    [modifiedon] DATETIME,
    [modifiedonbehalfby] UNIQUEIDENTIFIER,
    [modifiedonbehalfbyname] NVARCHAR(200),
    [modifiedonbehalfbyyominame] NVARCHAR(200),
    [name] NVARCHAR(100),
    [overriddencreatedon] DATETIME,
    [ownerid] UNIQUEIDENTIFIER,
    [owneridname] NVARCHAR(200),
    [owneridtype] NVARCHAR(64),
    [owneridyominame] NVARCHAR(200),
    [owningbusinessunit] UNIQUEIDENTIFIER,
    [owningteam] UNIQUEIDENTIFIER,
    [owninguser] UNIQUEIDENTIFIER,
    [resource] UNIQUEIDENTIFIER,
    [resourcecategory] UNIQUEIDENTIFIER,
    [resourcecategoryname] NVARCHAR(100),
    [resourcename] NVARCHAR(100),
    [statecode] INT,
    [statecodename] NVARCHAR(255),
    [statuscode] INT,
    [statuscodename] NVARCHAR(255),
    [timezoneruleversionnumber] INT,
    [transactioncurrencyid] UNIQUEIDENTIFIER,
    [transactioncurrencyidname] NVARCHAR(100),
    [utcconversiontimezonecode] INT,
    [versionnumber] BIGINT
)
=======
GO
>>>>>>> ab1fe2ce787ec7e2ffc2833bad1b5d5eba36b033
