/****** Object:  Table [dbo].[01_IIS_DATA_CONSOLIDATION]    Script Date: 2021-03-25 9:30:08 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

DROP TABLE IF EXISTS [dbo].[01_IIS_DATA_CONSOLIDATION];
CREATE TABLE [dbo].[01_IIS_DATA_CONSOLIDATION] (
	[COMPLETED] [nvarchar](10) NULL,
	[ASSIGNED_TO] [nvarchar](100) NULL,
	[IIS_ID] [numeric](18, 0) NULL,
	[COMPANY_NAME_FORMATTED] [nvarchar](500) NULL,
	[PLANNED2021] [nvarchar](10) NULL,
	[COMPANY_NAME] [nvarchar](500) NULL,
	[COUNTRY_SUBDIVISION_CD] [nvarchar](10) NULL,
	[CITY_TOWN_NAME_NM] [nvarchar](250) NULL,
	[ADDRESS] [nvarchar](1000) NULL,
	[POSTAL_CODE_TXT] [nvarchar](10) NULL,
	[FILE_STATUS_CD] [nvarchar](50) NULL,
	[SOUNDEX_NAME] [nvarchar](50) NULL,
	[MATCHING_ID] [numeric](18, 0) NULL,
	[FUZZY_MATCH] [nvarchar](500) NULL,
	[REGULATED_ENTITY_ID] [nvarchar](50) NULL,
	[REGULATED_ENTITY_NAME] [nvarchar](500) NULL,
	[CONSOLIDATED_COMMON_ENGLISH_NAME] [nvarchar](500) NULL,
	[CONSOLIDATED_COMMON_FRENCH_NAME] [nvarchar](500) NULL,
	[NOTES] [nvarchar](500) NULL
) ON [PRIMARY]
GO

DROP TABLE IF EXISTS [dbo].[02_REGULATED_ENTITIES];
CREATE TABLE [dbo].[02_REGULATED_ENTITIES] (
	[REGULATED_ENTITY_ID] [uniqueidentifier],
	[REGULATED_ENTITY_ID_SOURCE] [nvarchar](50) NULL,
	[IIS_ID] [numeric](18, 0) NULL,
	[REGULATED_ENTITY_NAME] [nvarchar](500) NULL,
	[CONSOLIDATED_COMMON_ENGLISH_NAME] [nvarchar](500) NULL,
	[CONSOLIDATED_COMMON_FRENCH_NAME] [nvarchar](500) NULL,
	[COUNTRY_SUBDIVISION_CD] [nvarchar](10) NULL,
	[CITY_TOWN_NAME_NM] [nvarchar](250) NULL,
	[ADDRESS] [nvarchar](1000) NULL,
	[POSTAL_CODE_TXT] [nvarchar](10) NULL,
	[COMPLETED] [nvarchar](10) NULL,
	[NOTES] [nvarchar](500) NULL
) ON [PRIMARY]
GO

DROP TABLE IF EXISTS [dbo].[03_SITES];
CREATE TABLE [dbo].[03_SITES] (
    [SITE_ID] [uniqueidentifier],
	[IIS_ID] [numeric](18, 0) NULL,
	[REGULATED_ENTITY_ID] [uniqueidentifier],
	[REGULATED_ENTITY_ID_SOURCE] [nvarchar](50) NULL,
	[COMPANY_NAME_FORMATTED] [nvarchar](500) NULL,
	[COMPANY_NAME] [nvarchar](500) NULL,
	[COUNTRY_SUBDIVISION_CD] [nvarchar](10) NULL,
	[CITY_TOWN_NAME_NM] [nvarchar](250) NULL,
	[ADDRESS] [nvarchar](1000) NULL,
	[POSTAL_CODE_TXT] [nvarchar](10) NULL,
	[COMPLETED] [nvarchar](10) NULL,
	[PLANNED2021] [nvarchar](10) NULL,
) ON [PRIMARY]
GO