------------------------------------------------
--CONVERT EXCEL DATA TO UNIQUE RECORDS WITH ADDRESS FROM "MATCHING_ID"
------------------------------------------------
TRUNCATE TABLE DBO.[02_REGULATED_ENTITIES];

INSERT INTO DBO.[02_REGULATED_ENTITIES]
(
	[REGULATED_ENTITY_ID],
	[REGULATED_ENTITY_ID_SOURCE],
	[REGULATED_ENTITY_NAME],
	[CONSOLIDATED_COMMON_ENGLISH_NAME],
	[CONSOLIDATED_COMMON_FRENCH_NAME]
)
SELECT
	NEWID(),
	REGENT.REGULATED_ENTITY_ID,
	TRIM(REGENT.REGULATED_ENTITY_NAME_LOGIC),
	TRIM(REGENT.CONSOLIDATED_COMMON_ENGLISH_NAME),
	TRIM(REGENT.CONSOLIDATED_COMMON_FRENCH_NAME)
FROM 
(

	--USE CONSOLIDATED COMMON NAME TO IDENTIFY REGULATED ENTITIES
	SELECT REGULATED_ENTITY_ID, REGULATED_ENTITY_NAME_LOGIC, CONSOLIDATED_COMMON_ENGLISH_NAME, CONSOLIDATED_COMMON_FRENCH_NAME, COUNT(REGULATED_ENTITY_ID) COUNT_OF
	FROM (
		SELECT REGULATED_ENTITY_ID, 
	
		CASE 
			WHEN CONSOLIDATED_COMMON_ENGLISH_NAME IS NULL THEN CONSOLIDATED_COMMON_FRENCH_NAME
			ELSE CONSOLIDATED_COMMON_ENGLISH_NAME
		END AS REGULATED_ENTITY_NAME_LOGIC, 
	
		CONSOLIDATED_COMMON_ENGLISH_NAME, 
		CONSOLIDATED_COMMON_FRENCH_NAME
	
		FROM [dbo].[01_IIS_DATA_CONSOLIDATION]
	) REGENT_NAMES WHERE REGULATED_ENTITY_NAME_LOGIC IS NOT NULL
	GROUP BY REGULATED_ENTITY_ID, REGULATED_ENTITY_NAME_LOGIC, CONSOLIDATED_COMMON_ENGLISH_NAME, CONSOLIDATED_COMMON_FRENCH_NAME
	HAVING COUNT(REGULATED_ENTITY_ID) > 1

) REGENT


------------------------------------------------
--CONVERT REGULATED ENTITY RECORDS TO ACCOUNTS--
------------------------------------------------

TRUNCATE TABLE [dbo].[04_ACCOUNT];

INSERT INTO [dbo].[04_ACCOUNT]
(
[accountnumber],
[description],
id,
accountid,
[ovs_legalname],
[name],
[ovs_accountnameenglish],
[ovs_accountnamefrench],
[owningteam],
[owningbusinessunit],
[owneridtype],
[ownerid],
[customertypecode]
)
SELECT
[REGULATED_ENTITY_ID_SOURCE]											[accountnumber],
CONCAT('Converted from IIS.', CHAR(13)+CHAR(10), 'Consolidation ID: ', 
[REGULATED_ENTITY_ID_SOURCE])											[description],
[REGULATED_ENTITY_ID]													id,
[REGULATED_ENTITY_ID]													[accountid],
[REGULATED_ENTITY_NAME]													[ovs_legalname],
[REGULATED_ENTITY_NAME]													[name],
[CONSOLIDATED_COMMON_ENGLISH_NAME]										[ovs_accountnameenglish],
[CONSOLIDATED_COMMON_FRENCH_NAME]										[ovs_accountnamefrench],
'd0483132-b964-eb11-a812-000d3af38846'									[owningteam],
'4e122e0c-73f3-ea11-a815-000d3af3ac0d'									[owningbusinessunit],
'team'																	[owneridtype],
'd0483132-b964-eb11-a812-000d3af38846'									[ownerid],
948010000																[customertypecode]
FROM [dbo].[02_REGULATED_ENTITIES] REGENT
WHERE [REGULATED_ENTITY_ID] = '4c338857-f76d-4b5d-97e9-4b542a318263'