/****** Object:  Table [dbo].[STAGING__ovs_cyaction]    Script Date: 2021-07-05 9:23:55 PM ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[STAGING__ovs_cyaction]') AND type in (N'U'))
DROP TABLE [dbo].[STAGING__ovs_cyaction]
GO

/****** Object:  Table [dbo].[STAGING__ovs_cyaction]    Script Date: 2021-07-05 9:23:55 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[STAGING__ovs_cyaction](
	[Id] [uniqueidentifier] NOT NULL,
	[SinkCreatedOn] [datetime] NULL,
	[SinkModifiedOn] [datetime] NULL,
	[statecode] [int] NULL,
	[statuscode] [int] NULL,
	[community] [int] NULL,
	[instancetypecode] [int] NULL,
	[ovs_actiontype] [int] NULL,
	[deliveryprioritycode] [int] NULL,
	[prioritycode] [int] NULL,
	[ovs_reasonmoc] [bit] NULL,
	[ovs_casereportjudgecommentsind] [bit] NULL,
	[isworkflowcreated] [bit] NULL,
	[ovs_evidencesaamples] [bit] NULL,
	[isbilled] [bit] NULL,
	[isregularactivity] [bit] NULL,
	[ovs_evidencephotos] [bit] NULL,
	[ovs_reasonhoti] [bit] NULL,
	[ovs_casereportcourtorderind] [bit] NULL,
	[ovs_evidencestatements] [bit] NULL,
	[leftvoicemail] [bit] NULL,
	[ovs_evidencedocuments] [bit] NULL,
	[ismapiprivate] [bit] NULL,
	[slaid] [uniqueidentifier] NULL,
	[slaid_entitytype] [nvarchar](128) NULL,
	[owningbusinessunit] [uniqueidentifier] NULL,
	[owningbusinessunit_entitytype] [nvarchar](128) NULL,
	[createdonbehalfby] [uniqueidentifier] NULL,
	[createdonbehalfby_entitytype] [nvarchar](128) NULL,
	[modifiedby] [uniqueidentifier] NULL,
	[modifiedby_entitytype] [nvarchar](128) NULL,
	[modifiedonbehalfby] [uniqueidentifier] NULL,
	[modifiedonbehalfby_entitytype] [nvarchar](128) NULL,
	[owninguser] [uniqueidentifier] NULL,
	[owninguser_entitytype] [nvarchar](128) NULL,
	[sendermailboxid] [uniqueidentifier] NULL,
	[sendermailboxid_entitytype] [nvarchar](128) NULL,
	[regardingobjectid] [uniqueidentifier] NULL,
	[regardingobjectid_entitytype] [nvarchar](128) NULL,
	[owningteam] [uniqueidentifier] NULL,
	[owningteam_entitytype] [nvarchar](128) NULL,
	[slainvokedid] [uniqueidentifier] NULL,
	[slainvokedid_entitytype] [nvarchar](128) NULL,
	[transactioncurrencyid] [uniqueidentifier] NULL,
	[transactioncurrencyid_entitytype] [nvarchar](128) NULL,
	[createdby] [uniqueidentifier] NULL,
	[createdby_entitytype] [nvarchar](128) NULL,
	[ovs_safetyassessmentid] [uniqueidentifier] NULL,
	[ovs_safetyassessmentid_entitytype] [nvarchar](128) NULL,
	[serviceid] [uniqueidentifier] NULL,
	[serviceid_entitytype] [nvarchar](128) NULL,
	[ownerid] [uniqueidentifier] NULL,
	[ownerid_entitytype] [nvarchar](128) NULL,
	[requiredattendees] [uniqueidentifier] NULL,
	[organizer] [uniqueidentifier] NULL,
	[from] [uniqueidentifier] NULL,
	[partners] [uniqueidentifier] NULL,
	[resources] [uniqueidentifier] NULL,
	[to] [uniqueidentifier] NULL,
	[cc] [uniqueidentifier] NULL,
	[customers] [uniqueidentifier] NULL,
	[optionalattendees] [uniqueidentifier] NULL,
	[bcc] [uniqueidentifier] NULL,
	[scheduledend] [datetime] NULL,
	[modifiedon] [datetime] NULL,
	[scheduledstart] [datetime] NULL,
	[senton] [datetime] NULL,
	[modifiedbyyominame] [nvarchar](100) NULL,
	[activityadditionalparams] [nvarchar](max) NULL,
	[ovs_directiontxt] [nvarchar](max) NULL,
	[seriesid] [uniqueidentifier] NULL,
	[transactioncurrencyidname] [nvarchar](100) NULL,
	[exchangeweblink] [nvarchar](1250) NULL,
	[activityid] [uniqueidentifier] NULL,
	[owneridtype] [nvarchar](4000) NULL,
	[postponeactivityprocessinguntil] [datetime] NULL,
	[ovs_investigationdetails] [nvarchar](max) NULL,
	[ovs_casereporttrialdate] [datetime] NULL,
	[ovs_noncompliancedetailstxt] [nvarchar](max) NULL,
	[ovs_dg_text_en] [nvarchar](max) NULL,
	[onholdtime] [int] NULL,
	[ovs_dgdescription] [nvarchar](max) NULL,
	[ovs_casereportnbr] [nvarchar](50) NULL,
	[ovs_actiondate] [datetime] NULL,
	[ovs_investigationsynopsis] [nvarchar](max) NULL,
	[ovs_revocationjustificationtxt] [nvarchar](max) NULL,
	[ovs_casereportjudgetxt] [nvarchar](max) NULL,
	[exchangeitemid] [nvarchar](200) NULL,
	[actualstart] [datetime] NULL,
	[serviceidname] [nvarchar](100) NULL,
	[owneridyominame] [nvarchar](100) NULL,
	[createdon] [datetime] NULL,
	[description] [nvarchar](max) NULL,
	[ovs_designatedperson] [nvarchar](100) NULL,
	[ovs_statusjustification] [nvarchar](max) NULL,
	[ovs_localtime] [nvarchar](100) NULL,
	[traversedpath] [nvarchar](1250) NULL,
	[ovs_dg_text_fr] [nvarchar](max) NULL,
	[sortdate] [datetime] NULL,
	[createdonbehalfbyname] [nvarchar](100) NULL,
	[ovs_offenses] [nvarchar](max) NULL,
	[modifiedonbehalfbyname] [nvarchar](100) NULL,
	[createdonbehalfbyyominame] [nvarchar](100) NULL,
	[ovs_casereportdescriptiontxt] [nvarchar](max) NULL,
	[actualend] [datetime] NULL,
	[regardingobjectidname] [nvarchar](400) NULL,
	[processid] [uniqueidentifier] NULL,
	[activitytypecode] [nvarchar](4000) NULL,
	[ovs_fineamt] [decimal](38, 2) NULL,
	[slainvokedidname] [nvarchar](100) NULL,
	[sendermailboxidname] [nvarchar](100) NULL,
	[ovs_blobpath] [nvarchar](200) NULL,
	[deliverylastattemptedon] [datetime] NULL,
	[ovs_actionnumber] [nvarchar](200) NULL,
	[subject] [nvarchar](400) NULL,
	[ovs_designatedpersontitle] [nvarchar](100) NULL,
	[timezoneruleversionnumber] [int] NULL,
	[createdbyname] [nvarchar](100) NULL,
	[actualdurationminutes] [int] NULL,
	[lastonholdtime] [datetime] NULL,
	[modifiedonbehalfbyyominame] [nvarchar](100) NULL,
	[ovs_ticketid] [nvarchar](20) NULL,
	[regardingobjectidyominame] [nvarchar](400) NULL,
	[regardingobjecttypecode] [nvarchar](4000) NULL,
	[stageid] [uniqueidentifier] NULL,
	[utcconversiontimezonecode] [int] NULL,
	[scheduleddurationminutes] [int] NULL,
	[ovs_interventionsummarytxt] [nvarchar](4000) NULL,
	[ovs_safetyassessmentidname] [nvarchar](100) NULL,
	[importsequencenumber] [int] NULL,
	[ovs_mocdescription] [nvarchar](max) NULL,
	[ovs_provisiontxt] [nvarchar](2000) NULL,
	[versionnumber] [bigint] NULL,
	[ovs_moc_text_en] [nvarchar](max) NULL,
	[ovs_moc_text_fr] [nvarchar](max) NULL,
	[ovs_releasedate] [datetime] NULL,
	[modifiedbyname] [nvarchar](100) NULL,
	[createdbyyominame] [nvarchar](100) NULL,
	[owneridname] [nvarchar](100) NULL,
	[overriddencreatedon] [datetime] NULL,
	[slaname] [nvarchar](100) NULL,
	[exchangerate] [decimal](38, 10) NULL,
 CONSTRAINT [EPK[dbo]].[STAGING__ovs_cyaction]]] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO



/****** Object:  Table [dbo].[STAGING__ovs_enforcementactionviolation]    Script Date: 2021-07-05 9:21:49 PM ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[STAGING__ovs_enforcementactionviolation]') AND type in (N'U'))
DROP TABLE [dbo].[STAGING__ovs_enforcementactionviolation]
GO

/****** Object:  Table [dbo].[STAGING__ovs_enforcementactionviolation]    Script Date: 2021-07-05 9:21:49 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[STAGING__ovs_enforcementactionviolation](
	[Id] [uniqueidentifier] NOT NULL,
	[SinkCreatedOn] [datetime] NULL,
	[SinkModifiedOn] [datetime] NULL,
	[statecode] [int] NULL,
	[statuscode] [int] NULL,
	[modifiedonbehalfby] [uniqueidentifier] NULL,
	[modifiedonbehalfby_entitytype] [nvarchar](128) NULL,
	[owningteam] [uniqueidentifier] NULL,
	[owningteam_entitytype] [nvarchar](128) NULL,
	[owninguser] [uniqueidentifier] NULL,
	[owninguser_entitytype] [nvarchar](128) NULL,
	[createdonbehalfby] [uniqueidentifier] NULL,
	[createdonbehalfby_entitytype] [nvarchar](128) NULL,
	[ovs_syresultid] [uniqueidentifier] NULL,
	[ovs_syresultid_entitytype] [nvarchar](128) NULL,
	[owningbusinessunit] [uniqueidentifier] NULL,
	[owningbusinessunit_entitytype] [nvarchar](128) NULL,
	[modifiedby] [uniqueidentifier] NULL,
	[modifiedby_entitytype] [nvarchar](128) NULL,
	[createdby] [uniqueidentifier] NULL,
	[createdby_entitytype] [nvarchar](128) NULL,
	[ovs_cyactionid] [uniqueidentifier] NULL,
	[ovs_cyactionid_entitytype] [nvarchar](128) NULL,
	[ownerid] [uniqueidentifier] NULL,
	[ownerid_entitytype] [nvarchar](128) NULL,
	[createdonbehalfbyyominame] [nvarchar](100) NULL,
	[owneridname] [nvarchar](100) NULL,
	[ovs_cyactionidname] [nvarchar](400) NULL,
	[ovs_enforcementactionviolationid] [uniqueidentifier] NULL,
	[importsequencenumber] [int] NULL,
	[modifiedbyyominame] [nvarchar](100) NULL,
	[utcconversiontimezonecode] [int] NULL,
	[createdbyyominame] [nvarchar](100) NULL,
	[ovs_name] [nvarchar](100) NULL,
	[versionnumber] [bigint] NULL,
	[timezoneruleversionnumber] [int] NULL,
	[modifiedbyname] [nvarchar](100) NULL,
	[owneridtype] [nvarchar](4000) NULL,
	[ovs_syresultidname] [nvarchar](300) NULL,
	[owneridyominame] [nvarchar](100) NULL,
	[modifiedon] [datetime] NULL,
	[modifiedonbehalfbyyominame] [nvarchar](100) NULL,
	[createdbyname] [nvarchar](100) NULL,
	[createdon] [datetime] NULL,
	[createdonbehalfbyname] [nvarchar](100) NULL,
	[modifiedonbehalfbyname] [nvarchar](100) NULL,
	[overriddencreatedon] [datetime] NULL,
 CONSTRAINT [EPK[dbo]].[STAGING__ovs_enforcementactionviolation]]] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


