--TRUNCATE TABLE [dbo].[20_LEGISLATION_MATCHING];

	DROP TABLE #TEMP_INSPECTIONS;

	--get violations and enforcement actions into temp table
    SELECT 
    YD095.FILE_NUMBER_NUM, 
    TD001.FILE_STATUS_ETXT, 
    TD001.FILE_STATUS_FTXT,	
    TD045.ACTIVITY_TYPE_ENM, 
    TD045.ACTIVITY_TYPE_FNM, 
    YD040.INSPECTION_DATE_DTE, 
    YD040.ACTIVITY_ID, 
    YD040.STAKEHOLDER_ID, 
    TD045.ACTIVITY_TYPE_CD, 
    TD038.INSPECTION_REASON_ETXT, 
    TD038.INSPECTION_REASON_FTXT,
    VIOLATIONS.VIOLATION_CD,
	VIOLATIONS.VIOLATION_COMMENTS_TXT,
	VIOLATIONS.MOC_SERIAL_NUMBER_NUM,
	VIOLATIONS.MOC_TYPE_CD, 
	VIOLATIONS.MOC_VIOLATION_COMMENTS_TXT, 
	VIOLATIONS.TDG_SPECIFICATION_CD, 
	VIOLATIONS.UN_NUMBER_ID
	--,ENFORCEMENT_ACTIONS.ENFORCEMENT_ACTION_TYPE_CD

	INTO #TEMP_INSPECTIONS

    FROM YD040_ACTIVITY YD040
    INNER JOIN YD095_STAKEHOLDER_FILE YD095 ON  YD040.FILE_NUMBER_NUM = YD095.FILE_NUMBER_NUM  
    INNER JOIN YD101_FILE_ACTIVITY_TYPE YD101 ON YD101.FILE_NUMBER_NUM = YD095.FILE_NUMBER_NUM AND YD101.DATE_DELETED_DTE IS NULL
    INNER JOIN TD045_ACTIVITY_TYPE TD045 ON YD101.ACTIVITY_TYPE_CD = TD045.ACTIVITY_TYPE_CD 
    INNER JOIN TD001_FILE_STATUS TD001 ON YD095.FILE_STATUS_CD = TD001.FILE_STATUS_CD  
    LEFT JOIN YD041_INSPECTION YD041 ON YD040.ACTIVITY_ID = YD041.ACTIVITY_ID 
    LEFT JOIN TD038_INSPECTION_REASON TD038 ON YD041.INSPECTION_REASON_CD = TD038.INSPECTION_REASON_CD 
    
    LEFT JOIN
    (
        SELECT YD020.ACTIVITY_ID,
        YD020.VIOLATION_CD,
		YD020.VIOLATION_COMMENTS_TXT,
		YD021.MOC_SERIAL_NUMBER_NUM,
		YD021.MOC_TYPE_CD, 
		YD021.MOC_VIOLATION_COMMENTS_TXT, 
		YD021.TDG_SPECIFICATION_CD, 
		YD021.UN_NUMBER_ID
        FROM YD020_INSPECTION_VIOLATION YD020
		LEFT JOIN YD021_MOCLIST YD021 ON YD020.ACTIVITY_ID = YD021.ACTIVITY_ID AND YD020.VIOLATION_CD = YD021.VIOLATION_CD
        WHERE YD020.DATE_DELETED_DTE IS NULL
    ) VIOLATIONS ON VIOLATIONS.ACTIVITY_ID = YD040.ACTIVITY_ID
    
    
    --LEFT JOIN
    --(
    --    SELECT YD023.ACTIVITY_ID,
    --    YD023.ENFORCEMENT_ACTION_TYPE_CD
    --    FROM YD023_VIOL_ENFORCEMENT_ACTION YD023 
    --    WHERE YD023.DATE_DELETED_DTE IS NULL
    --    GROUP BY YD023.ACTIVITY_ID, YD023.ENFORCEMENT_ACTION_TYPE_CD
    --) ENFORCEMENT_ACTIONS ON ENFORCEMENT_ACTIONS.ACTIVITY_ID = YD040.ACTIVITY_ID
    
    WHERE 
    YD040.DATE_DELETED_DTE IS NULL AND 
    YD095.DATE_DELETED_DTE IS NULL AND 
    YD041.DATE_DELETED_DTE IS NULL AND 
    YD101.DATE_DELETED_DTE IS NULL 
    --AND TD045.ACTIVITY_TYPE_PARENT_CD IS NULL 
    GROUP BY 
    YD095.FILE_NUMBER_NUM, 
    TD001.FILE_STATUS_ETXT, 
    TD001.FILE_STATUS_FTXT, 
    TD045.ACTIVITY_TYPE_ENM, 
    TD045.ACTIVITY_TYPE_FNM, 
    YD040.INSPECTION_DATE_DTE, 
    YD040.ACTIVITY_ID, 
    YD040.STAKEHOLDER_ID, 
    TD045.ACTIVITY_TYPE_CD, 
    TD038.INSPECTION_REASON_ETXT, 
    TD038.INSPECTION_REASON_FTXT,
    VIOLATIONS.VIOLATION_CD,
	VIOLATIONS.VIOLATION_COMMENTS_TXT,
	VIOLATIONS.MOC_SERIAL_NUMBER_NUM,
	VIOLATIONS.MOC_TYPE_CD, 
	VIOLATIONS.MOC_VIOLATION_COMMENTS_TXT, 
	VIOLATIONS.TDG_SPECIFICATION_CD, 
	VIOLATIONS.UN_NUMBER_ID;
	--,ENFORCEMENT_ACTIONS.ENFORCEMENT_ACTION_TYPE_CD;


	DROP TABLE #TEMP_VIOLATIONS;

	SELECT
	ACTIVITY_ID, 
	STAKEHOLDER_ID,
	T3.LegislationId,
	T3.Label,
	T3.Name,
	T3.[English Text],
	T1.VIOLATION_CD, 
	T1.VIOLATION_COMMENTS_TXT,
	T1.MOC_SERIAL_NUMBER_NUM,
	T1.MOC_TYPE_CD, 
	T1.MOC_VIOLATION_COMMENTS_TXT, 
	T1.TDG_SPECIFICATION_CD, 
	T1.UN_NUMBER_ID,
	T2.VIOLATION_REFERENCE_CD,
	T4.msdyn_workorderid,
	CAST(T4.msdyn_workordersummary as nvarchar(4000)) msdyn_workordersummary,
	T4.msdyn_address1,
	T4.msdyn_address2,
	T4.msdyn_address3,
	T4.msdyn_addressname,
	T4.msdyn_name,
	T4.msdyn_postalcode,
	T4.msdyn_serviceaccount,
	T4.msdyn_serviceterritory,
	T4.ovs_iisid,
	T4.qm_reportcontactid
	INTO #TEMP_VIOLATIONS
	FROM #TEMP_INSPECTIONS T1
	JOIN [dbo].[TD070_VIOLATION] T2 ON T1.VIOLATION_CD = T2.VIOLATION_CD
	JOIN [20_LEGISLATION_MATCHING] T3 ON T2.VIOLATION_CD = T3.VIOLATION_CD
	JOIN [06_WORK_ORDERS] T4 ON CAST(T4.msdyn_workordersummary as nvarchar(MAX)) = CAST(T1.ACTIVITY_ID as nvarchar(MAX));


	--SELECT DISTINCT * FROM #TEMP_VIOLATIONS;
	
TRUNCATE TABLE [07_VIOLATIONS];

INSERT INTO [dbo].[07_VIOLATIONS]
           (
			[qm_syresultid]
           ,[qm_externalcomments]
		   ,[qm_internalcomments]
           ,[qm_isviolation]
           ,[qm_name]
           ,[qm_rclegislationid]
           ,[qm_referenceid]
           ,[qm_violationcount]
           ,[qm_workorderid]
		   ,[ownerid]
           ,[owneridtype]
           ,[owningbusinessunit]
           ,[owningteam])



SELECT

newid(), 

CASE
WHEN MOC_VIOLATION_COMMENTS_TXT IS NULL OR TRIM(MOC_VIOLATION_COMMENTS_TXT) = '' THEN VIOLATION_COMMENTS_TXT 
ELSE CONCAT(T1.VIOLATION_COMMENTS_TXT, CHAR(13)+CHAR(10), 'MOC', CHAR(13)+CHAR(10), T1.MOC_VIOLATION_COMMENTS_TXT)
END,

CONCAT(
	CASE WHEN MOC_SERIAL_NUMBER_NUM IS NULL THEN '' ELSE CONCAT('MOC_SERIAL_NUMBER_NUM=', MOC_SERIAL_NUMBER_NUM, ';') END, 
	CASE WHEN MOC_TYPE_CD IS NULL			THEN '' ELSE CONCAT('MOC_TYPE_CD=', MOC_TYPE_CD, ';') END, 
	CASE WHEN TDG_SPECIFICATION_CD IS NULL	THEN '' ELSE CONCAT('TDG_SPECIFICATION_CD=', TDG_SPECIFICATION_CD, ';') END, 
	CASE WHEN UN_NUMBER_ID IS NULL			THEN '' ELSE CONCAT('UN_NUMBER_ID=', UN_NUMBER_ID, ';') END
),

1, 

CASE 
WHEN MOC_SERIAL_NUMBER_NUM IS NULL OR TRIM(MOC_SERIAL_NUMBER_NUM) = '' THEN TRIM([Label]) 
ELSE CONCAT(TRIM([Label]), ' - ', MOC_SERIAL_NUMBER_NUM)
END, 

LegislationId,
MOC_SERIAL_NUMBER_NUM,
1, 
msdyn_workorderid,
'd0483132-b964-eb11-a812-000d3af38846'									[ownerid],
'team'																	[owneridtype],
'4e122e0c-73f3-ea11-a815-000d3af3ac0d'									[owningbusinessunit],
'd0483132-b964-eb11-a812-000d3af38846'									[owningteam]
FROM
(
	SELECT DISTINCT * FROM #TEMP_VIOLATIONS
) T1
