/****** Object:  Table [dbo].[ACTIVITY_TYPE_MAPPINGS]    Script Date: 2021-07-14 5:13:28 PM ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ACTIVITY_TYPE_MAPPINGS]') AND type in (N'U'))
DROP TABLE [dbo].[ACTIVITY_TYPE_MAPPINGS]
GO
/****** Object:  Table [dbo].[ACTIVITY_TYPE_MAPPINGS]    Script Date: 2021-07-14 5:13:28 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ACTIVITY_TYPE_MAPPINGS](
	[IIS_ACTIVITY_TYPE_ID] [int] NULL,
	[IIS_ACTIVITY_TYPE_ENM] [varchar](37) NOT NULL,
	[IIS_ACTIVITY_SUB_TYPE_ID] [int] NULL,
	[IIS_ACTIVITY_SUB_TYPE_ENM] [varchar](52) NOT NULL,
	[ROM_OVERSIGHT_TYPE_ID] [varchar](50) NULL,
	[ROM_OVERSIGHT_TYPE_ENM] [varchar](30) NOT NULL,
	[ROM_RATIONALE_ID] [varchar](50) NULL,
	[ROM_RATIONALE_ENM] [varchar](9) NOT NULL
) ON [PRIMARY]
GO
INSERT [dbo].[ACTIVITY_TYPE_MAPPINGS] ([IIS_ACTIVITY_TYPE_ID], [IIS_ACTIVITY_TYPE_ENM], [IIS_ACTIVITY_SUB_TYPE_ID], [IIS_ACTIVITY_SUB_TYPE_ENM], [ROM_OVERSIGHT_TYPE_ID], [ROM_OVERSIGHT_TYPE_ENM], [ROM_RATIONALE_ID], [ROM_RATIONALE_ENM]) VALUES (20, N'Site visit', NULL, N'n/a', N'SITE_VISIT', N'SITE_VISIT', N'994C3EC1-C104-EB11-A813-000D3AF3A7A7', N'Planned')
GO
INSERT [dbo].[ACTIVITY_TYPE_MAPPINGS] ([IIS_ACTIVITY_TYPE_ID], [IIS_ACTIVITY_TYPE_ENM], [IIS_ACTIVITY_SUB_TYPE_ID], [IIS_ACTIVITY_SUB_TYPE_ENM], [ROM_OVERSIGHT_TYPE_ID], [ROM_OVERSIGHT_TYPE_ENM], [ROM_RATIONALE_ID], [ROM_RATIONALE_ENM]) VALUES (21, N'General Compliance Inspection', 25, N'Scheduled (Workplan / Risk Based - excluding others)', N'50D0BDF1-269E-EB11-B1AC-000D3AE924D1', N'GC IPT', N'994C3EC1-C104-EB11-A813-000D3AF3A7A7', N'Planned')
GO
INSERT [dbo].[ACTIVITY_TYPE_MAPPINGS] ([IIS_ACTIVITY_TYPE_ID], [IIS_ACTIVITY_TYPE_ENM], [IIS_ACTIVITY_SUB_TYPE_ID], [IIS_ACTIVITY_SUB_TYPE_ENM], [ROM_OVERSIGHT_TYPE_ID], [ROM_OVERSIGHT_TYPE_ENM], [ROM_RATIONALE_ID], [ROM_RATIONALE_ENM]) VALUES (21, N'General Compliance Inspection', 26, N'Compliance Estimation Program (CEP)', N'72afccd3-269e-eb11-b1ac-000d3ae924d1', N'GC Targeted', N'994C3EC1-C104-EB11-A813-000D3AF3A7A7', N'Planned')
GO
INSERT [dbo].[ACTIVITY_TYPE_MAPPINGS] ([IIS_ACTIVITY_TYPE_ID], [IIS_ACTIVITY_TYPE_ENM], [IIS_ACTIVITY_SUB_TYPE_ID], [IIS_ACTIVITY_SUB_TYPE_ENM], [ROM_OVERSIGHT_TYPE_ID], [ROM_OVERSIGHT_TYPE_ENM], [ROM_RATIONALE_ID], [ROM_RATIONALE_ENM]) VALUES (21, N'General Compliance Inspection', 27, N'Follow-up Inspection (Indicated)', N'72afccd3-269e-eb11-b1ac-000d3ae924d1', N'GC Targeted', N'994C3EC1-C104-EB11-A813-000D3AF3A7A7', N'Planned')
GO
INSERT [dbo].[ACTIVITY_TYPE_MAPPINGS] ([IIS_ACTIVITY_TYPE_ID], [IIS_ACTIVITY_TYPE_ENM], [IIS_ACTIVITY_SUB_TYPE_ID], [IIS_ACTIVITY_SUB_TYPE_ENM], [ROM_OVERSIGHT_TYPE_ID], [ROM_OVERSIGHT_TYPE_ENM], [ROM_RATIONALE_ID], [ROM_RATIONALE_ENM]) VALUES (21, N'General Compliance Inspection', 28, N'Follow-up Inspection (Discretionary)', N'72afccd3-269e-eb11-b1ac-000d3ae924d1', N'GC Targeted', N'994C3EC1-C104-EB11-A813-000D3AF3A7A7', N'Planned')
GO
INSERT [dbo].[ACTIVITY_TYPE_MAPPINGS] ([IIS_ACTIVITY_TYPE_ID], [IIS_ACTIVITY_TYPE_ENM], [IIS_ACTIVITY_SUB_TYPE_ID], [IIS_ACTIVITY_SUB_TYPE_ENM], [ROM_OVERSIGHT_TYPE_ID], [ROM_OVERSIGHT_TYPE_ENM], [ROM_RATIONALE_ID], [ROM_RATIONALE_ENM]) VALUES (21, N'General Compliance Inspection', 32, N'Triggered', N'9dee7316-5f9c-eb11-b1ac-000d3ae92708', N'GC Triggered', N'47F438C7-C104-EB11-A813-000D3AF3A7A7', N'Unplanned')
GO
INSERT [dbo].[ACTIVITY_TYPE_MAPPINGS] ([IIS_ACTIVITY_TYPE_ID], [IIS_ACTIVITY_TYPE_ENM], [IIS_ACTIVITY_SUB_TYPE_ID], [IIS_ACTIVITY_SUB_TYPE_ENM], [ROM_OVERSIGHT_TYPE_ID], [ROM_OVERSIGHT_TYPE_ENM], [ROM_RATIONALE_ID], [ROM_RATIONALE_ENM]) VALUES (21, N'General Compliance Inspection', 33, N'Opportunity', N'07966e1c-5f9c-eb11-b1ac-000d3ae92708', N'GC Opportunity', N'47F438C7-C104-EB11-A813-000D3AF3A7A7', N'Unplanned')
GO
INSERT [dbo].[ACTIVITY_TYPE_MAPPINGS] ([IIS_ACTIVITY_TYPE_ID], [IIS_ACTIVITY_TYPE_ENM], [IIS_ACTIVITY_SUB_TYPE_ID], [IIS_ACTIVITY_SUB_TYPE_ENM], [ROM_OVERSIGHT_TYPE_ID], [ROM_OVERSIGHT_TYPE_ENM], [ROM_RATIONALE_ID], [ROM_RATIONALE_ENM]) VALUES (22, N'MOC Facility Inspection (Planned)', NULL, N'all subcategory types', N'e99ab21b-279e-eb11-b1ac-000d3ae924d1', N'MOC Facility IPT', N'994C3EC1-C104-EB11-A813-000D3AF3A7A7', N'Planned')
GO
INSERT [dbo].[ACTIVITY_TYPE_MAPPINGS] ([IIS_ACTIVITY_TYPE_ID], [IIS_ACTIVITY_TYPE_ENM], [IIS_ACTIVITY_SUB_TYPE_ID], [IIS_ACTIVITY_SUB_TYPE_ENM], [ROM_OVERSIGHT_TYPE_ID], [ROM_OVERSIGHT_TYPE_ENM], [ROM_RATIONALE_ID], [ROM_RATIONALE_ENM]) VALUES (23, N'Consignment', NULL, N'all subcategory types', N'460B6C2A-5F9C-EB11-B1AC-000D3AE92708', N'GC Consignment', N'47F438C7-C104-EB11-A813-000D3AF3A7A7', N'Unplanned')
GO
INSERT [dbo].[ACTIVITY_TYPE_MAPPINGS] ([IIS_ACTIVITY_TYPE_ID], [IIS_ACTIVITY_TYPE_ENM], [IIS_ACTIVITY_SUB_TYPE_ID], [IIS_ACTIVITY_SUB_TYPE_ENM], [ROM_OVERSIGHT_TYPE_ID], [ROM_OVERSIGHT_TYPE_ENM], [ROM_RATIONALE_ID], [ROM_RATIONALE_ENM]) VALUES (24, N'Document Review', NULL, N'n/a', N'A4965081-5F9C-EB11-B1AC-000D3AE92708', N'Civil Aviation Document Review', N'47F438C7-C104-EB11-A813-000D3AF3A7A7', N'Unplanned')
GO
INSERT [dbo].[ACTIVITY_TYPE_MAPPINGS] ([IIS_ACTIVITY_TYPE_ID], [IIS_ACTIVITY_TYPE_ENM], [IIS_ACTIVITY_SUB_TYPE_ID], [IIS_ACTIVITY_SUB_TYPE_ENM], [ROM_OVERSIGHT_TYPE_ID], [ROM_OVERSIGHT_TYPE_ENM], [ROM_RATIONALE_ID], [ROM_RATIONALE_ENM]) VALUES (59, N'MOC Facility Inspection - (Unplanned)', NULL, N'all subcategory types', N'F6A0B96E-5F9C-EB11-B1AC-000D3AE92708', N'MOC Facility Opportunity', N'47F438C7-C104-EB11-A813-000D3AF3A7A7', N'Unplanned')
GO
