//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDG.CORE.ETL.RESOURCES.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TDG.CORE.ETL.RESOURCES.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;!DOCTYPE Regulation PUBLIC &quot;-//Justice Canada//DTD Regulation v1.2.2//EN&quot; &quot;Dtd/Regulations/RCM/Regulation.dtd&quot;&gt;&lt;Regulation gazette-part=&quot;II&quot; regulation-type=&quot;SOR&quot; xml:lang=&quot;fr&quot; xmlns:lims=&quot;http://justice.gc.ca/lims&quot;&gt;&lt;Identification&gt;&lt;InstrumentNumber&gt;DORS/2001-286&lt;/InstrumentNumber&gt;&lt;RegistrationDate&gt;&lt;Date&gt;&lt;YYYY&gt;2001&lt;/YYYY&gt;&lt;MM&gt;8&lt;/MM&gt;&lt;DD&gt;1&lt;/DD&gt;&lt;/Date&gt;&lt;/RegistrationDate&gt;&lt;ConsolidationDate&gt;&lt;Date&gt;&lt;YYYY&gt;2020&lt;/YYYY&gt;&lt;MM&gt;7&lt;/MM&gt;&lt;DD&gt;16&lt;/DD&gt;&lt;/Date&gt;&lt;/ConsolidationDate&gt;&lt;EnablingAutho [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DORS_2001_286 {
            get {
                return ResourceManager.GetString("DORS_2001_286", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] GeneralCompliance {
            get {
                object obj = ResourceManager.GetObject("GeneralCompliance", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] GeneralCompliance_V2 {
            get {
                object obj = ResourceManager.GetObject("GeneralCompliance_V2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;!DOCTYPE Regulation PUBLIC &quot;-//Justice Canada//DTD Regulation v1.2.2//EN&quot; &quot;Dtd/Regulations/RCM/Regulation.dtd&quot;&gt;&lt;Regulation xmlns:xml=&quot;http://www.w3.org/XML/1998/namespace&quot; gazette-part=&quot;II&quot; regulation-type=&quot;SOR&quot; xml:lang=&quot;en&quot; xmlns:lims=&quot;http://justice.gc.ca/lims&quot;&gt;&lt;Identification&gt;&lt;InstrumentNumber&gt;SOR/2001-286&lt;/InstrumentNumber&gt;&lt;RegistrationDate&gt;&lt;Date&gt;&lt;YYYY&gt;2001&lt;/YYYY&gt;&lt;MM&gt;8&lt;/MM&gt;&lt;DD&gt;1&lt;/DD&gt;&lt;/Date&gt;&lt;/RegistrationDate&gt;&lt;ConsolidationDate&gt;&lt;Date&gt;&lt;YYYY&gt;2020&lt;/YYYY&gt;&lt;MM&gt;7&lt;/MM&gt;&lt;DD&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SOR_2001_286 {
            get {
                return ResourceManager.GetString("SOR_2001_286", resourceCulture);
            }
        }
    }
}
